### ISSUE TITLE
Read results from .sql file

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#148]
@chriswmackey I thought that you maybe interested in the file that I developed during the hackathon as the starting point: https://www.dropbox.com/s/gg0rlcu3wx8pbfe/readSQL.gh

**Comment by chriswmackey** [comment]
I'm not going to be able to get this done for the release but I will look into it afterwards.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey do we even need this now that you implemented custom result reader for EnergyPlus?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I was thinking this myself.  I can't think of what else the SQL will add that the custom result reader and RDD parsing component do not offer.  Then again I don't know the uses of SQL as much.  If you can't think of anything, may be we just close out the issue?

**Comment by mostaphaRoudsari** [comment]
Let's close this for now. It will come up again when we move all the development to OpenStudio.

**Comment by chriswmackey** [comment]
Sounds good.

**Comment by mostaphaRoudsari** [comment]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1677965

**Comment by chriswmackey** [comment]
I posted a response of why I don't think the SQL is a good way of addressing the issue brought up in the GH discussion (and showed the better way to address this issue with the custom result reader now).  Feel free to reopen the issue, @mostaphaRoudsari , if you think I'm misinterpreting anything or if you have reasons for why the SQL method is better than the one that I posted.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I read your response and as you said it addresses all we need currently. I think we still will be developing the functionalities to read sql files for Honeybee[+]. I understand your concerns about the speed of the process but at the same time it's an efficient way of parsing results for larger files. Let's discuss this more when we are in the place to get this implemented.

**Comment by chriswmackey** [comment]
@mostapharoudsari ,
Sounds good. I agree that there is value in using the SQL format, especially if it allows us to easily do things like import all results for 1 zone in a multi-zone model or import results for just 1 HVAC node without having to import the hundreds that can existing in a model. I think that we need to fuse it with the way we request inputs for the CSV format, though, so that people still have the flexibity of deciding what the want to write into the file. We can discuss more when we get to it on HB[+] and let's open an issue there with regards to implementing it.

**Comment by chriswmackey** [comment]
I made a new issue here:
https://github.com/ladybug-analysis-tools/honeybee/issues/123
