### ISSUE TITLE
Add Energy Performance Calculator (EPC) component to Honeybee

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#191]
We had a good conversation this week with P+W research team and they proposed to work on a new component for Honeybee to support EPC method. The method looks promising for initial stages of design and is pretty fast. Here is a PhD thesis which describes the methodology: https://smartech.gatech.edu/handle/1853/43580

The current workflow is using an excel spreadsheet which will be finally replace by the new component. The first step is to develop an exporter from Honeybee objects that provides enough information for EPC so they can get started with the process.

**Comment by saeranv** [comment]
@mostaphaRoudsari I'm on the P+W Research team (with @antonszilasi) , and we've internally discussed phasing out the EPC method due to it's inability to consider latent loads (Anton can probably give you more info about this). Who were you working on this with at P+W? I can see if there was any progress done with this component, but if not, perhaps we can consider closing this issue.

**Comment by mostaphaRoudsari** [comment]
Hi @saeranv, We started this with @pchopson and @sahuja9. I think they both have left P+W.

@pchopson and @sahuja9, any updates on this? Are you still trying to fully implement the method in python? otherwise, we can close this issue and remove the component as it currently just returns the area for surfaces.

**Comment by mostaphaRoudsari** [comment]
ok. I'm closing this for now. @pchopson and @sahuja9 if you're interested in working on this please open a new issue and we can start this over.
