### ISSUE TITLE
LightDensityPerAreaCalculator (new)

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#200]
What do you think?
https://www.dropbox.com/s/bv6uwz38y2yp6uv/LightDensityPerAreaCalculator.gh?dl=0
-A.

**Comment by chriswmackey** [comment]
@ayezioro,
I am just letting you know that we intend to include the lighting density per area calculator in the upcoming stable release and I have committed a preliminary version.  I hope you don't mid that I added some of the information that you had gathered in the neighboring list component to the description of the component input.
I also put in a default bulb type of florescent tubes and default maintenance values that correspond with information that you had in the descriptions (Since I imagine that I will not know these values exactly until the end of a project, more often than not).
If the component in this file looks ok, we should be all set:
https://www.dropbox.com/s/d8wi93w9ee5lkf6/LightDensityPerAreaCalculatorCWM.gh?dl=0
-Chris

**Comment by ayezioro** [comment]
Great.
If you see the file in:
https://www.dropbox.com/s/pkiw2rvrjkvn9vt/ACH2m3_s-m2%2BLightDensityPerAreaCalculator.gh?dl=0
I updated the file according to your new defaults but there is also a component ACH2m3/s-m2 Calculator, so you can give ACH and it will calculate for you the m3/s-m2, which i find much more complicated to know. If you find this component useful you can include it also.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Excellent job!  I committed both components to the "08 | Energy | Set Zone Properties" tab and they are good to go for the next release.  As such, I am closing out this issue.
-Chris
