### ISSUE TITLE
Natural ventilation implementation to HBZone class

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#239]
Hi @chriswmackey, We need to add all the new properties for natural ventilation to HBZone class and also re-evaluateHBZone. It is missing right now.

In general a good practice is to remove all the direct assignments and write set/get methods for the properties.

http://www.grasshopper3d.com/xn/detail/2985220:Comment:1197226

**Comment by mostaphaRoudsari** [comment]
It was already there and overwritten in one of the recent commits. It is fixed now!

**Comment by chriswmackey** [comment]
Awesome.  Good to know.  For general reference, all of the nat vent attributes that I added are lists that are introduced in the init part of the HBZone class.  The components that add nat vent features just add things to the lists and the Run EnergyPlus component just takes the content of these lists and writes them into the IDF.  I don't think that I need to write anything into re-evaluateHBZone but, if you think otherwise, just let me know.
