### ISSUE TITLE
HVACAvailabilitySched set to None?

### ISSUE THREAD

**Issue by chiensiTB** [mostaphaRoudsari/Honeybee#250]
I think this is a new schedule meant to address @chriswmackey  's issues for a user who requested it.  But by default, it appears this schedule is set to None?  Is this intentional?  Should it maybe instead be set to something like "Always On"?  (always set to 1)

**Comment by chriswmackey** [comment]
@chiensiTB ,
Good point.  With the ideal air loads template that the Run Simulation component uses, if the HVAC availability schedule is set to and empty string (''), it knows to have the HVAC always on.  I just changed it so that the value assigned to the zone is "ALWAYS ON" and I have changed the Run Simulation component accordingly. (https://github.com/mostaphaRoudsari/Honeybee/commit/78e4c95785178a8dc3229c68cd85fea05bea600e)

I am closing out this issue but feel free to re-open it if I misunderstood.
-Chris
