### ISSUE TITLE
New Run Energy Simulation component doesn't do version check!

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#252]
@chriswmackey just used the component in class and it failed as I had another version of Honeybee flying. I submit it as a bug since it looks that you almost always forget this! ;) Thanks!

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Thanks for letting me know.  A lot of the times it is hard for me to guess the right date if I have forgotten to change it in the past.  I guess I should just always keep it with the most recent LB and HB before I commit it and I will do this here on out.

I was under the impression that we might update the compatibility checks on all components before the stable release since I did not understand how the checks worked at first and I fear that there may be other examples of this out there (I would very much like to start-over with good habits).  Would it be possible to do this in the same script that updates the dates and version numbers of all the components? 

-Chris

**Comment by mostaphaRoudsari** [comment]
Hey @chriswmackey, it is possible to have it as a part of versions and date and I will update it for each major release but meanwhile you have to take care of it yourself similar to dates.

You only need to change the  line for HB and Ladybug version check when the update involves some changes to Honeybee_Honeybee or Ladybug_Ladybug components. Otherwise the component will work fine with older versions and there is no need to change the date.

I hope this helps to clarify the process. Let me know if you are still not clear why and when you need to change the version check.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I'm glad to hear that we can update all of the version checks. I have understood how they are supposed to work for the past month or so but I still forget a lot. While I know that I only need to do it when HB updates, I think that I have to make a habit out of it each time I commit or else I'll forget to do it when it is important.
-Chris
