### ISSUE TITLE
AirTempMap error

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#266]
Hi,
This component is failing when i connect the RelativeHumidity input. I get:
1. Solution exception:index out of range: 0

I see also that there are a couple of inputs more that i don't know from where to get them: _zoneAirFlowVol and _zoneAirHeatGain. It says that they are supposed to be outputs from the EP Read Results, but i don't see them.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Man, you are on top of changes as soon as I make them.  The air map is not really at a state to be tested or applied yet.  In fact, in another week or two, I am going to do away with the component and have all indoor comfort analysis done through the "Annual Indoor Comfort Analysis" component.  I am mostly using the air map and radiation map components right now as training wheels for developing this larger workflow.  Until yesterday, the air map was not giving accurate estimates for stratification (or it was basically assuming that stratification was always 2C).  The map now approximates stratification using a method developed by a PhD student at my school:
http://dspace.mit.edu/handle/1721.1/74907

Since this issue is not going to be relevant in another week, I am closing this for now.  If you really need the component in this week, I have fixed the error and you can get the _zoneAirFlowVol and _zoneAirHeatGain inputs from the EPResultReader.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey that's an exact use of Github to keep track of tasks, I would have left it opened until I get it fixed. Just don't assign it to a mile-stone.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I fixed the issue, though. The component no longer fails in @ayezioro 's case. If we want to open another issue for the major revamping of the cMap components that I am in the middle of, that might make more sense than keeping this one open.

-Chris

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by ayezioro** [comment]
Thanks Chris,
I'm having problem getting it to work. I mean: It is not giving an error now, but i'm not getting the outputs from EPReadResults. Of course this is a matter of ignorance on my side about how to define things to get these outputs.
In the example i'm using the NatVent component.
-A.

**Comment by chriswmackey** [comment]
I'll post an example file soon.  It's going to be one that is just for the github, though, since this component is really not something that I want the masses to be using yet.

**Comment by chriswmackey** [comment]
@ayezioro ,
The new comfort map workflow is complete.  See an example file here:
https://www.dropbox.com/s/rpty2ff9992ko5n/Indoor%20Temperature%20Map19.gh?dl=0

![indoormicroclimatemap](https://cloud.githubusercontent.com/assets/5567574/6072151/43cb5b36-ad6c-11e4-9dad-fa2e16022470.PNG)

Enjoy and let me know any feedback.
-Chris

**Comment by ayezioro** [comment]
Hi Chris,
This is awesome. I'll check further on.
I noticed that instead of defining a distance from surface you have those two planes. Nice. I"ll try to make this interactive ...
I understand that the spaces should be unconditioned to get this to work. Thinking of situations that a mixed situations can be desired: HVAC but if outdoor conditions allow use the night ventilation. There can be other scenarios ...
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes, you can now input any surface on which you want to view micro-climates; ranging all of the way from a small area representing the place where a single person might sit all of the way to taking an entire micro-climate section through a complete building (just input one surface that slices through the whole building and the component will know how to split it up).
The spaces do not have to be unconditioned but I have found that the maps are particularly useful for buildings where there is no HVAC (since your major design constraint is comfort and you can make the argument that, as long as some part of the space is comfortable at a given hour, the occupant might be able to find it and be happy).
Note that if you are using in cases with heating/cooling and you are imagining that the HVAC system will be with forced air, you might want to set the "wellMixedAirOverride" to true since forced air systems tend to eliminate the stratification profile in a room.
-Chris

**Comment by ayezioro** [comment]
Hi Chris,
I'm struggling right now with this issue (conditioned/unconditioned). I don't want to define something beyond IdealSystem. The thing is i'm not getting at the EPResults neither the airFlowVolume, nor airHeatGainRate outputs, which are a must for the PMV/Adaptive comfort recipies.
I'm not sure what input i need to set in order to receive those outputs ...?
Any clues here?
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

Make sure that you are using the new "Honeybee_Generate EP Output" component and not the old "Write EP Result Parameters" component.  I am sorry for the confusion that changing the name made but "Write EP Result Parameters" made me cringe every time I saw it.

It's almost as bad as the names that EnergyPlus has for some of its outputs like:
Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate

-Chris

**Comment by ayezioro** [comment]
Ahhhhh!!
Whenever i updated the file i didn't pay attention to such details. Devil is in them :-)
It is working now (of course). With the airTemp you see nicely the stratification temperatures. 
Thanks,
-A.
