### ISSUE TITLE
Separate by orientation failed when I created masses using split mass

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#271]
I guess it is a problem with window surface normal which I need to check

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I believe that this should be fixed by now thanks to the extra "rhino-baking" check that I do at the end of splitBuildingMass and by the good general normal-checking functions that I have put in for HBSrfs.  I am going to close out the issue but feel free to re-open if you think that stuff that I put in did not fix it.
-Chris
