### ISSUE TITLE
Add lookupFolder for energy simulation

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#273]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1220805

**Comment by ayezioro** [comment]
OK.
I picked the glove and came out with this version:
https://www.dropbox.com/s/ih48euu6pzdfudk/ParametricEnergy.gh?dl=0
Please have a look and suggest/change what you think is good to make it work better.
The file includes an example with minimum complexity (on the side of the E+ simulation parameters).

There are soem questions in the code regarding issues i didn't understand, python wise.
What do you think? ... I think is nice :-)
-A.

**Comment by arkdanielnielsen** [comment]
Really good idea with lockup folder comp for E+! Even though it have similarity to "Import idf" expect for the result file.
I have tried it, but there is a error (maybe what your are asking about @ayezioro ) "1. Solution exception:WindowsError"?
There is little spelling mistake in the "Args: under 5 > Energy Plus" Suppose it should be 6 instead.

**Comment by ayezioro** [comment]
Hi Daniel,
Didn't get the error you mention. Do you see the line where this is happening?
Didn't get either the "import idf". Can you explain?
Thanks,
-A.

**Comment by arkdanielnielsen** [comment]
1) Error: there is only written  "1. Solution exception:WindowsError" as seen in the image.
2) The component "Import IDF". It import HBzones but not the result file (.csv).
3) the spelling mistake is in line 20.
![honeybee_epfolder-lookup-01](https://cloud.githubusercontent.com/assets/7299731/6134308/a370b598-b160-11e4-8c6f-a5777b91952d.jpg)

**Comment by ayezioro** [comment]
Hmmm ...
I can't reproduce your error but i get other from my own.
I'll ask Mostapha's help to discover those.
At first i was thinking that your panel folder is wrong. I believe you have there one of the results folders that they are not supposed to be there. So i input just "c:\018" (please try this also). But then i get a different error (1. Solution exception:name 'idfresultFiles' is not defined. The 018 folder in my computer is empty).
There are plenty of Python stuff i don't know ... so be patient.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham and Daniel and thank you!

Abraham - 
You were trying to do two different steps in a single component.
1. Find all sub-folders
2. find files inside sub-folders.

I broke them into two separate steps so it is more clear now and it will work in both cases either the user have all the runs in a single folder or they are in separate folders.

![image](https://cloud.githubusercontent.com/assets/2915573/6141082/92288316-b16e-11e4-9bd7-460a2148f25e.png)

Back to the questions:

exec in python converts a string to a command. I was using it to send the data to the right output after changing the name of the output. If you check Daylighting lookup component you will notice that the output name changes between resultFiles and illFiles for studies. In this example I don't think we need that.

I also changed the types to only be EnergyPlus and OpenStudio and added two new outputs for .osm and .sql file but I didn't write the code.

Now you have two components to commit! :)

Here is the file: https://www.dropbox.com/s/ctwwd3uw3dolgj9/ParametricEnergy_msr.gh?dl=0

**Comment by chriswmackey** [comment]
@ayezioro ,
This is a great idea and thanks for taking up the initiative.  Thanks also, Mostapha for getting it in shape.  I have a few requests when you can get around to them, Abraham:

1) Right now, I have the EnergyPlus run automatically generate an .rdd file, which is basically a file that lists all of the possible outputs that you can get from a certain simulation.  I was thinking to build a component to parse this file and put them in the format that the RunEnergyPlus component would understand (I imagine people wanting some non-standard outputs eventually).  If you include the .rdd file on this lookup component, I will build the parser component.

2) It would be great to get any of the csv schedules that are written to the result folder to come out of this component (if possible).  I understand that, right now, there is not much that you can do with the csv file on its own but I had plans to make the "schedule to values" component able to take a csv file and turn it into a bunch of values that can be visualized with the LB components. If you bring the csv schedules in with this lookup folder, I will build the functionality into the "schedule to values" component.

-Chris

**Comment by ayezioro** [comment]
Hi Mostapha and Chris,
Chris: Already added the RDD (and many others just in case: err, eio, eso, sql). Here it is: https://www.dropbox.com/s/7r9ijbv9uzyguk1/ParametricEnergy_01.gh?dl=0
Regarding the schedules i want to coordinate with you. Since they are CSV i don't want to mix them with the results file. I was thinking adding automatically to the schedule files a "_SCH" before the extension so i can identify them. If you have a better idea how to differentiate results from schedules  let me know.

Mostapha: THANKS!! Though i'm not happy of having 2 components for this. I'll still try to do the job only with one ... unless you think this will mess things. Will let you know how i'm doing.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. As far as I understand having them together won't work for honeybee folders. Current structure is to have a root folder for each project and then subfolders for each study type.
If you out them together in a single component then it will be only useful if user run all the studies under another parent folder (in your example parametric runs) otherwise it won't work.

Also it should be consistent with the one for daylighting.

I think it's a better idea to break them down into two unless you find a better solution.

**Comment by arkdanielnielsen** [comment]
I have a question about handling subfolders/files better. I have been running a lot of different simulation types. Everything works fine when you run energyPlus and Annual Daylight. They are placed fine in the main folder "018" with sublfolders and energyPlus and annualSimulation with the naming "F.7m_W.33_U.90_S.40_T.60". The problem occur when running different time steps, because at that point I want or need to put more info into the naming like ".... + M3_T9". These time step simulations would be nice to place in the "main" subfolder "F.7m_W.33_U.90_S.40_T.60" where I have the other simulations. To do that there should be a option of controlling this more flexible.
![honeybee_folder-subfolders-01](https://cloud.githubusercontent.com/assets/7299731/6150770/a21cb1ae-b211-11e4-8bd4-936ba7600734.JPG)

**Comment by ayezioro** [comment]
OK Mostapha. Get your challenge.
You HAVE to like this. I updated the previous file so please download it again.
I won't explain what i did. You'll understand easily. Of course cleaning up comments are more than welcome.
-A.

**Comment by ayezioro** [comment]
Hi,
Until you respond i have a small question. What is this doing:
try: ghenv.Component.AdditionalHelpFromDocStrings = "1"
Does it makes any difference the number at the end?
-A.

**Comment by ayezioro** [comment]
And another one. I've found one lick in the component. Is in the CSV output. The example i used (the attached above) don't use schedules. In case you define one or more you'll get them as CSV at the folder and they will be at the output list. So the question is how to get rid of them and have only the one with the results.
I was thinking to extract the name from the StudyFolder. In either case i'll  need your help to do that.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
To answer your first question, the number at the end of the line is used to help place the component in a section of the  "09 | Energy | Energy" tab (or any other tab for that matter).  It gets read by the "Ladybug_Export Ladybug" component when committing new components.  So that line there is telling it to place the component in the first section but you can put it in any of the other 5 that are there.  Also "0" denotes a component that only appears in the drop-down from the tab.

For your second question, I do not understand.  Does there need to be only one CSV file? Can't you just bring in all of the schedule CSV files as a list?

Glad to hear that the .rdd is already there and I'll get on a parser soon unless you beat me to it.  I just added a default "SHC" at the start of any CSV schedule written with the "Create CSV Schedule" component so you should be good to go.
![image](https://cloud.githubusercontent.com/assets/5567574/6180092/513a946c-b2ee-11e4-9e66-62727e7f77a3.png)

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
Q1: OK. understood.
Q2: My original intention is to output the csv file of the results. Like the one in the HB_runEnergySimulation. So i can plot the results aftewrwards. In the examp,e above it works fine since i didn't define any schedule. But now i'm doing it in another file and then the outputs gives all of the CSV's in the simulation folder. So i want to differentiate the schedules CSV from the results.
Later on (today, i hope) i'll try to takle the "SCH". If it will work that will solve Q2 also.
As for the RDD didn't get the output you expect. I know there are the "whole" possible outputs. But still something is not clear to me.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham, et. al.
Well... Looks like I have no choice but to like this so I will :). but you need to give me two more days. It has been two crazy weeks and I have to travel tomorrow morning and also teach! I will check it during the weekend. :zzz:

**Comment by ayezioro** [comment]
Well guys, I think is ready. Please "break" it (hope you can't).
I added a new output for schedules. For this one i'm not sure the way i'm outputting is the best one since you can get a long list of them when you run parametrics. So probably i need to separate them by case (suggestions?).
Same link as above ...
-A.

**Comment by mostaphaRoudsari** [comment]
Nicely done Abraham! I couldn't break it for EnergyPlus but there are two other :beetle: cases:

1. It doesn't work for OpenStudio. The structure for OpenStudio folders is slightly different so you probably need to make some modifications to the code.

![image](https://cloud.githubusercontent.com/assets/2915573/6200076/9778da18-b435-11e4-86c7-e63b34ae4773.png)

2. You need to catch wrong types and give a warning! Right now it crashes the component. In the version that I sent last time I was checking type%2 for this reason.
![image](https://cloud.githubusercontent.com/assets/2915573/6200078/a94bcfe8-b435-11e4-990c-f5be107d2a8b.png)

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen can you open a new issue for folders structure. I agree with you that we need to get this fixed! Thanks.

**Comment by ayezioro** [comment]
Oich!!!. When i was thinking i'm done ... :-(
Well. I"ll do but you need to do too:
The LookupFolder_Daylighting also fails when the studyType is not in the range.
The exportToOpenStudio output files don't fit the runEnergySimulation. They are always "in.extension". It can stay this way but maybe you think it doesn't.
In the same component the meterFileAddress point to insz.csv instead of in,csv.
-A.

**Comment by ayezioro** [comment]
Hi again,
Mostapha: The structure for OS cases is not slightly different. is quite significant. Before i go on (already started), i want to ask if this structurre is to be reconsidered to be more consistent to the EP's.
The hierarchy is like this:
![capture](https://cloud.githubusercontent.com/assets/7526023/6202989/6cce6c92-b511-11e4-9944-53cf03798c05.JPG)
As you can see, in my opinion, there is at least one spear folder (ModelToIdf). There is a redundancy (in my opinion, again) with the directory name of the OS case. The names of the files in the ModelToIdf are not related to the case name. The best (for me) is to conserve the hierarchy of the EP case and having all the names under the EP or OS folders.
Does it make any sense?
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham.

Thanks for finding the bug. I will fix that. If there was a degree for bug finding you would be qualified for a PhD w/o going to school. ;)

We are using OpenStudioAPI to generate and run the analysis with OpenStudio so we don't really have control on the structure of the folder. ModelToIdf is generated by OpenStudio during the execution so I think you have to deal with different structures here.

**Comment by ayezioro** [comment]
Make me laugh ... but don't know why ...
I understand that the folder "CaseName OS" will be eliminated and "ModelToIdf" will go up one floor? Or is it also a OS constrain? (Hope not).
Waiting for your confirmation on this one before going on.
-A.

**Comment by mostaphaRoudsari** [comment]
As far as I can see how you have it up there is right. It creates a folder by caseName.

![image](https://cloud.githubusercontent.com/assets/2915573/6204607/64a63e6a-b51f-11e4-914c-4e57bde26e6a.png)

**Comment by ayezioro** [comment]
So it is what i was afraid of ...
The structure is T H E structure.
OK. I'll go ahead.
-A.

**Comment by mostaphaRoudsari** [comment]
lol. I can check and see if there is a way to overwrite the structure later if it is making so much trouble but for now it is what we got!

**Comment by ayezioro** [comment]
Don't worry. We will win with this (as we say here) :-)

**Comment by ayezioro** [comment]
Hi,
Didn't forget, but since you released the Pollinator i was thinking that this is a good example o use it.
Do you mind having a look? Daniel and Chris: You too.
Please see the 2 options i did. Not sure which one is more efficient (if any) or you have a better suggestion. If ok, it can be added to the examples folder.
The link:
https://www.dropbox.com/s/j5cakmydozbajxo/ParametricEnergy_01%2BPollinator.gh?dl=0
-A.

**Comment by arkdanielnielsen** [comment]
First of all @mostaphaRoudsari cool new development with the Pollinator!
@ayezioro really good example! I think both examples is good. I some cases I think option 2 is better to check if all data is written correct.
1) With the parametric runs I have just done I should have though of the recording component. Because when having a lot of runs you want to find out the min/max values from all your simulations. For this the recording component is a really good method! Would it be useful with a component to take the min/max values? Instead of doing it "manually" as @ayezioro have done.
2) An improvement to the Pollinator workflow could be a component that read/write the simulation type like some of the daylight components with unit output. Maybe it could be a extra output from the "Ladybug_Separate data"? Or in the "Ladybug_Average Data"? Or in even both of them?

**Comment by ayezioro** [comment]
Hi @mostaphaRoudsari @arkdanielnielsen @chriswmackey 
I send a request for this component. Can you check if i did right. This github environment is not very friendly ... for now.
Anyway, i think i finished the component that allows to look up for E+/OS results contained in one folder. As similar to the Daylight one.
Is maybe not the most elegant but it is a working component. All Mostapha's request are there ... i think.
I believe the component will answer, at least partly, to many request from the last few days regarding retrieving results in quantities.
So please give it a try and if you consider it is fine you can release it to the air.
This example can help: https://www.dropbox.com/s/mj1q65mngk73v9i/ParametricEnergy_02a.gh?dl=0 . You need to let the FLY permission to take off. Also set the simulation components to True (E+ and OS). You should get 8 directories for each type (16 over all). It will run fast so don't be worried about this.
Any suggestions for improving the code are more than welcome.
Thanks,
-A.

**Comment by ayezioro** [comment]
As for the broken link, this is weird, but if you google waterslade (https://www.google.co.il/search?q=waterslade&ie=utf-8&oe=utf-8&gws_rd=cr&ei=GDOuVum3BIb9sQHdzae4BA) you'll get the main page. Look there for the "dev_potential" image.
So weird.
-A.

**Comment by ayezioro** [comment]
Hi,
Just want to be sure i did right.
Did you get my pull request for this new component?
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
The pull request is not showing up on the Master Branch of the repository:
https://github.com/mostaphaRoudsari/Honeybee/pulls
You may have sent a pull request in the opposite direction.  Let me know if you have difficulty figuring it out and I can show you quickly over skype.
-Chris

**Comment by ayezioro** [comment]
Thanks Chris,
I think i did it. Can you check please?
In any case i'll appreciate if you check the example and test the component workflow.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes, I see it and it is looking good.  I am going to merge it now and test out the workflow.  I might also move a couple of my components around to make this better fit in the toolbar.
-Chris

**Comment by ayezioro** [comment]
Great!! Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

The workflow really looks good.  My only edit is that you follow one of the minor points of the [Ladybug Graphic Standards](https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug%20Grahpic%20Standards.md) and you put in a line that calls the isInputMissing function like in the template file:
https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug_Component_Template.py#L85

Also, as your notation on _styduType_ suggests, you should have a default set for this value so that the user does not always have to connect something.  Ideally, I imagine that it would be nice to have the component auto-sense if there is only a single study type in the folder and import that info.  If both are there, maybe it defaults to OpenStuido?  I leave the call to you.

I am going to move the 'SurfaceDataBasedOnType' down below the tab to make room for your new component.  I am also going to add study folder outputs to the EnergyPlus and OpenStudio components.  I will post back here once its done.

Let me know if you have any difficulties/questions implementing the suggestions above and I can help.

It's so wonderful to finally have this component.  Great job, as always!
-Chris

**Comment by ayezioro** [comment]
Thanks Chris,
For the first part i'm not getting it. So please feel free to implement as needed ... or letting me understand better.
For the second part, i'll give it a try. I think i have an idea how to do it.
For the third part, excellent. Will be more consistent.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I finished adding in the study folder for the E+ and OS components:
https://github.com/mostaphaRoudsari/Honeybee/commit/072077b72c460f12242a94d9a05740e27cdec90e

This commit shows what I meant by updating to the recent template (I realized that it was more than one line that needed to be switched):
https://github.com/mostaphaRoudsari/Honeybee/commit/a8370cac51fff5042c4661b9bfdd558d4d25761c

In the future, starting with [this template](https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug_Component_Template.py) will ensure that all features that are supposed to be in the component show up.  It will do things like automatically checking the required inputs and giving a warning if they are not present, checking the version, and checking to be sure that LB+HB are flying.

Looking forward to the default studyType!
-Chris

**Comment by mostaphaRoudsari** [comment]
This is very useful! Thanks @ayezioro and @chriswmackey  :+1:
Should we close this issue then?

**Comment by ayezioro** [comment]
Not yet,
I still need to fix some default values ...
-A.

**Comment by ayezioro** [comment]
I've sent a pull request.
I settled making the studyType input as compulsory input.
Found a bit complicated to make some checkings instead.

Maybe later on i'll try harder ... :-(

-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
See my comments on your pull request. 
-Chris

**Comment by mostaphaRoudsari** [comment]
@ayezioro @chriswmackey should we close this issue?

**Comment by chriswmackey** [comment]
I thin @ayezioro should do the honors of closing the issue unless he thinks anything is missing.

**Comment by ayezioro** [comment]
Trying to close but i don't think i have the rights to do that.
Anyway, it can be closed.
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks Abraham. I close it on behalf of you.Thanks for taking care of this component.
