### ISSUE TITLE
IndoorComfAnalysis - Calculation has been terminated by the user!

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#281]
Hi Chris,
Following this closed issue: https://github.com/mostaphaRoudsari/Honeybee/issues/266
I'm getting this error in the HB_IndoorComfAnalysis component. For the example you attached and another one of mine works. But now i'm trying in another file and it gives this warning message.
![2015-02-15_20-42-38](https://cloud.githubusercontent.com/assets/7526023/6204426/561372f8-b553-11e4-93de-6e3f032be775.jpg)
What can be the reason?
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey is the one to answer to this but I can just tell you that this has been an issue before that he has fixed once: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1221209

Is it also happening if you set parallel to False?

**Comment by ayezioro** [comment]
I remember this discussion.
Yes, i tried Parallel false or disconnect it, but still ... the warning is there. Even though the image i sent shows otherwise ... :-(

**Comment by chriswmackey** [comment]
@ayezioro ,
This definitely smells like a bug.  Perhaps it's a division by zero somewhere that is triggering the loop to fail and the Esc key warning to pop up.  Could you upload your GH file?
-Chris

**Comment by ayezioro** [comment]
Sure:
https://www.dropbox.com/s/e3cbh32kfjbp955/Caldwell_01a.gh?dl=0
Plenty of stuff there. Sorry for that. Look at the right bottom of the spaghetti.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

My instinct was almost dead-on.  There was a math domain error because a negative number was being sent into a log function.  It was a bug affecting just the cases where you have a single zone that is high above the Rhino origin.  It is now fixed in the attached file and on the github:
![image](https://cloud.githubusercontent.com/assets/5567574/6205048/a66825b6-b52e-11e4-8fcb-04f9a07df27f.png)

https://www.dropbox.com/s/6l1it8uo3e0lnz3/Caldwell_01a_CWM.gh?dl=0
-Chris

**Comment by ayezioro** [comment]
Wow!! You are great!!
Thanks,
-A.
