### ISSUE TITLE
Insert genral HVAC in the model

### ISSUE THREAD

**Issue by FranZac1** [mostaphaRoudsari/Honeybee#283]
Hi!
I would like to insert a general HVAC for my model but I'm having some issues.
I need to insert a simple boiler and a simple chiller in order to do my tests;
After a very simple definition with the 'Hot water boiler' and 'EIR Chiller', I'm using the 'Central Plant Orchestrator' and further the 'openStudio system'.
But it is not working.
Anyone can help me?

![immagine](https://cloud.githubusercontent.com/assets/10981879/6211677/f638b53e-b5dc-11e4-91f3-04d646af21b3.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @FranZac1, This is a question for @chiensiTB but meanwhile can you also share your file? Just the part that you are showing here should be enough. Thanks.

**Comment by FranZac1** [comment]
No problem @mostaphaRoudsari! 

https://www.dropbox.com/sh/wl5ospladaj4zd6/AAAcXmjE690mFcogDkXzECtqa?dl=0
It should be a bit messy, but it shows all the steps needed to run a simulation with both E+ and OpenStudio;

Another little issue is linked to the 'air economizer' for E+; it seems not working properly (if I plot the graphs of heating and cooling I can see that there's heating load also in summertime). Maybe it happens because there's no component to adjust humidity. 

Moreover, it could be great to implement the OS simulation component, allowing it to accept .csv schedule.

Many thanks for your help!

**Comment by chriswmackey** [comment]
@FranZac1 ,

I should be able to fix the ideal air system's air economizer if that is where the problem that you are referring to is.  I don't understand, though.  An air side economizer just mixes in more of the outside air when there is a cooling need in winter.  I don't think it should affect the heating in summer (that's probably just the climate and setpoints that you are dealing with).

-Chris

**Comment by chiensiTB** [comment]
Hey there.  I apologize that I am only getting to this on the fourth day.  For some reason, there is something wrong with my github notifications, and my components are just now coming online and people are testing them.  

Anyhow @FranZac1, there were a couple of issues.  The first is that you had not plugged in the HVAC systemID into the central plant orchestrator, you used a panel with the string "HVAC".  Right now, I do not have any checking there and it does not throw an error, but it should!  Pretty easy fix, you want to plug in the systemTypeId just like you do for the OpenStudio Systems component.  The central plant orchestrator also needs to know which system type you wish to model...

Another thing, as of now, you really must define an air handler (this is a component in Honeybee section 10 (Air Handler Detail.  And this should be plugged into OpenStudio Systems as well.  It is not possible to run open studio without creating one of these air handlers and including it in the definition.  And you want to!!!  By default, OpenStudio does not do a very good job creating default fans, or airside economizers, and I have found that in order to get a good result, I always have to create fans and airside economizers, plug them into the Air Handler Detail, and then plug the output into OpenStudio Systems.

I know it might seem counter intuitive to have different components.  I hope this helps you.  I'll be releasing some videos shortly.  I am sending your component back to you, with the changes.  I also added an airside economizer for you, with some defaults in it.  You will want to read up on the availability manager (EnergyPlus documentation) because this is essential to making sure your air system is shutting down at the right times.  Otherwise, you get fans that run all night and some other nonsense which is not great for the result.  I would like to provide smarter defaults, but it is a bit tricky to know what the right smart default is.  Feel free to share your thoughts on how to improve smart defaults.

**Comment by chiensiTB** [comment]
PS- the air handler details is also where you can specify a 2-speed DX coil if your system type does not use a chiller.  Only system type 7 currently uses a chiller, by the way.  Otherwise, you can specify a chiller, but if the central plant orchestrator does not see type 7, it will ignore it.  As will all downstream components of OpenStudio.

**Comment by chiensiTB** [comment]
Here is your file.  @FranZac1 I would suggest updating your components often over the next few weeks, there will be changes often.

**Comment by chiensiTB** [comment]
https://www.dropbox.com/s/equcwmikpmu74ev/c%3D2%2C3_16022015.gh?dl=0

**Comment by jacoposartore** [comment]
hi @chiensiTB could you please reupload the file you provided, as it is no more available. Many thanks to you.

**Comment by mostaphaRoudsari** [comment]
```
Moreover, it could be great to implement the OS simulation component, allowing it to accept .csv schedule.
```
@FranZac1 sure! We do have an open issue for this (#161). OpenStudio API doesn't currently support this but there are workarounds for this.

FYI: @macumber

**Comment by chriswmackey** [comment]
@FranZac1 ,
For issues regarding the E+ ideal air loads economizer, you should check out this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/ideal-loads-outdoor-air-economizer
I have recently decided to remove the ideal air loads economizer because it sets misleading expectations.
-Chris
