### ISSUE TITLE
strange change of zone list when rotate geometry using slipt building mass 

### ISSUE THREAD

**Issue by agusHariyadi** [mostaphaRoudsari/honeybee#288]
@mostaphaRoudsari  @chriswmackey 
It's a bug or normal?
![44](https://cloud.githubusercontent.com/assets/6168707/6326774/64c424dc-bb98-11e4-800f-e30b4d63b1a8.JPG)
![45](https://cloud.githubusercontent.com/assets/6168707/6326778/6aaccbe2-bb98-11e4-96dd-39d12002fc05.JPG)

I think it will give wrong result when using it with "Pollination for exploring multi-dimensional data" (display data base on zone name) if we use rotation or orientation as dimension, or optimizing component like galapagos or something  if we use rotation as genome..
https://www.dropbox.com/s/lm52ato4lmsicwr/box1.gh?dl=0

**Comment by agusHariyadi** [comment]
I found that It's only happen with box geometry..the order of the list is consistent if we use extrude surface..
![r1](https://cloud.githubusercontent.com/assets/6168707/6366469/48d386ec-bd09-11e4-897b-7ceaef2feac0.JPG)
![r2](https://cloud.githubusercontent.com/assets/6168707/6366467/48d0f33c-bd09-11e4-97d6-ea99e7d19bd1.JPG)
so I change the input of the geometry, but it become more component to be used..
![solution](https://cloud.githubusercontent.com/assets/6168707/6366468/48d29908-bd09-11e4-81cd-782002d2c1a5.JPG)
my temporary solution.. https://www.dropbox.com/s/se7qi720jo94hhk/box2.gh?dl=0

**Comment by chriswmackey** [comment]
@agusHariyadi ,
I realize this issue was opened a long time ago and it probably had to do with the order of zones and names of zones not matching.  In this day and age, I would recommend using the Honeybee Transform components to do operations like this after the zones have been created.    Using the "Rotate Honeybee" component will help ensure preservation of the base zone names in the transformation.
