### ISSUE TITLE
Error of Color Zones and Surfaces by EP Result with Hourly timestep

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#303]
Hi there,

I'm getting this error

"1. Not all of the connected _zoneData branches are of the same length or there are more than 8760 values in the list."

when running simulations with both EnergyPlus (EP 8.2.0) and OpenStudio (EP 8.1.0) set to perform hourly time steps, whereas with a daily, monthly of annually selection it works flawlessly.

![hourly timestep error](https://cloud.githubusercontent.com/assets/8501837/6694699/3b7c2fde-ccdc-11e4-81be-79671db8fc54.png)

![daily timestep ok](https://cloud.githubusercontent.com/assets/8501837/6694700/3eb288d8-ccdc-11e4-9f63-a2e07caa270d.png)

Here is the GH definition (https://www.dropbox.com/s/kbgerx5tulwt0qw/Timestep%20Error.gh?dl=0).

**Comment by jacoposartore** [comment]
I managed to avoid the issue by removing the Honeybee_Simulation Control component.

**Comment by chriswmackey** [comment]
@jacoposartore ,
The issue you were getting was because setting "runSimfForSizingPeriods" to True adds the sizing period to the output data, hence messing up the 8760-hour annual structure that LB+HB depends on.  See below for a working file and i am closing out the issue as this seems to be resolved:
https://drive.google.com/file/d/0Bz2PwDvkjovJLUlSVkRRUl9GeG8/view?usp=sharing
-Chris

**Comment by jacoposartore** [comment]
Great! Thank you @chriswmackey.
