### ISSUE TITLE
Parse ep.err file and give a warning if there are sever errors

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#315]
Many users don't have the knowledge to understand the failure of EP simulation.

I think we should also do the same check in readResults component and give a better warning than no .eio file found. It can be something like no .eio file found. Based on the .err file in the folder the simulation hasn't run successfully. Check readMe! output of runEnergySimulation component. etc.

cc: @chriswmackey

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I was thinking about the same thing and that the warning really should be given on the Run Simulation component because that is where the error is occurring and not in the reading of a result file.

I feel that we should have the Run simulation component parse through the error file to find any severe / fatal errors.  If it finds a severe / fatal error, it should turn orange and possibly give the severe error as a warning on the component.  Also, I feel that the component should not output an address to a result file if none has been written as the result of a fatal error.

What do you think about this approach rather than editing the result reader?
-Chris

**Comment by mostaphaRoudsari** [comment]
Makes sense to me. I will add this once I get the issue with Daysim fixed. On the other hand, I think it doesn't hurt to have it on both components. Between the time that I posted this and now we got a new discussion with the same topic.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
You are right that the warnings that the Read EP component are usually not describing what the problem is.  I have since put in some better (albeit longer) warnings that include instructions for what users should do:
https://github.com/mostaphaRoudsari/Honeybee/commit/1912446d168f1f3e5b235104f0b3cce27ae01e7f
Let me know if you would like any help putting warnings into the Run Simulation component.  I think that both of these things will go a long way towards helping people.
-Chris

**Comment by chriswmackey** [comment]
I finally got tired of so many users not understanding what was going on.  I added severe errors to the component warning now:
![image](https://cloud.githubusercontent.com/assets/5567574/7245019/8a6227de-e7b2-11e4-989a-20fb80c1e851.png)

Issue closed

**Comment by antonszilasi** [comment]
Personally I stop the whole component with return -1 and print an error if something is amiss that will cause EnergyPlus to crash - I only just print errors if I assign default values - you've gotta make these things as bullet proof as possible

**Comment by chriswmackey** [comment]
Thanks for the input, @antonszilasi ,
This change was made specifically for the case where we didn't catch an error before the simulation ran but have found out later from the error report that the simulation was not successful.  I agree that, ideally, we should try to catch everything before running the simulation but we can't guarantee this in all cases (especially some very tricky geometry-related stuff).
-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! We really needed this.

**Comment by jacoposartore** [comment]
I have updated the runEnergySimulation component and I think that the warnings are really helpful. Unfortunately, I have found a small glitch: its reporting some severe errors even though there are just warnings:

1. The simulation has not run correctly because of this severe error: 
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
2. The simulation has not run correctly because of this severe error: 
   ************* EnergyPlus Sizing Error Summary. During Sizing: 1 Warning; 0 Severe Errors.
3. The simulation has not run correctly because of this severe error: 
   ************* EnergyPlus Completed Successfully-- 4 Warning; 0 Severe Errors; Elapsed Time=00hr 00min 13.00sec

I had to bypass the resultFileAddress output by concatenating some text notes in order to get the EP results.

**Comment by mostaphaRoudsari** [comment]
Thanks @jacoposartore for reporting. This should be an easy fix. I think right now @chriswmackey is looking for Severe in the line so he should make it more specific.

**Comment by jacoposartore** [comment]
You're welcome @mostaphaRoudsari.

**Comment by mostaphaRoudsari** [comment]
It should work fine now.

**Comment by jacoposartore** [comment]
It works now. Thank you.
