### ISSUE TITLE
Read EP HVAC Result error when visualizing OpenStudio results

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#325]
Hi there,

I'm opening this discussion following #304.

This component works fine when an Ideal Air Load System is selected,
![readephvacresult ideal air load](https://cloud.githubusercontent.com/assets/8501837/7112022/e22b655e-e1c5-11e4-90fa-fddce3cfdb80.png)
but it doesn't if one of the Central HVAC Systems is selected (Packaged VAV in this case).
![readephvacresult packaged vav](https://cloud.githubusercontent.com/assets/8501837/7112045/00d02d3c-e1c6-11e4-8906-87e0190f7a61.png)

The purpose of using this component is to import the zone-level heating and cooling loads when dealing with Central HVAC Systems. In addition @chriswmackey proposed to add the entries for zone-level sensible and latent heat values.

**Comment by chriswmackey** [comment]
@jacoposartore ,
I will get to this issue once I complete my thesis.  In the mean time, if you can find the names of the outputs in the rdd file produced after running the VAV simulation that would give you the zone level info that you want, that would save me a large amount of time going forward.  I know that there are a lot of different possible outputs that you can request with the VAV system and knowing the ones that you want will probably save time that would otherwise be spent trying different outputs.
-Chris

**Comment by jacoposartore** [comment]
Hi @chriswmackey,

As you suggested, I have checked the .rdd file to figure out which outputs would fit with my expectations. I did some OpenStudio tests on a couple of them and I think that those are the good ones:

'Zone Air System Sensible Cooling Energy'
![zone air system sensible cooling energy](https://cloud.githubusercontent.com/assets/8501837/7270331/d53dc374-e8db-11e4-9f6a-6c6cfe288e29.png)

'Zone Air System Sensible Heating Energy'
![zone air system sensible heating energy](https://cloud.githubusercontent.com/assets/8501837/7270332/d8af2926-e8db-11e4-8c4d-c40df140497f.png)

As you can see the results are consistent with what one would expect to happen.

I have also figured out that other outputs would be a good addition as, for example, 'Availability Manager Scheduled Control Status' and 'Plant System Cycle On Off Status': I believe that the Generate EP Output component should have more detailed options, with checklists like Ladybug's Passive Strategy List. Let me know your thoughts.

P.S. Good luck with your thesis, I'm sure you're doing great things.

**Comment by chriswmackey** [comment]
@jacoposartore ,
The issue with "Zone Air System Sensible Cooling Energy" is that it will give combined cooling that comes both from the cooling coil and from any outdoor air that is mixed into the supply air.  Usually, people want to know the cooling coming from just the coil and not the free cooling that you can get from mixing in cooler outdoor air with an economizer.
For heating output, I guess this is probably fine since the indoors are usually warmer than outdoors when you want to heat the building but there can also be rare cases where supply air from the outdoors can heat up the indoor space and so I would prefer not to use it.
Let me know if you agree and, if so, what outputs you would suggest otherwise.

I can put in some of those other outputs to the HVAC Params input.  A more detailed output checklist sounds useful but I really think that we should have it in addition to the current "Generate EP Output" component and not instead of it.

Thanks for wishing me luck on the thesis!

**Comment by jacoposartore** [comment]
Hi @chriswmackey,

I'm sorry for getting back so late, I was busy with my wedding and the honeymoon.

I agree with you that there should be a simple "Generate EP Output" component, as the current one, and an advanced one with a checklist.

As regards the "Zone Air System Sensible Cooling Energy", you are right: it's taking into account outside air and even the fans. Should we refer to "HVAC,Sum, Total Water Heating Coil Energy" and "HVAC,Sum,Cooling Coil Total Cooling Energy" or, simpler, to "Boiler Heating Energy" and "Chiller Electric Energy", which are considering the energy used to heat and cool the air within the AHU? The problem with this is that it's not calculated on a zone-level. I think that there should be a component able to retrieve this kind of data from central systems.

Let me know your thoughts.

**Comment by chriswmackey** [comment]
@jacoposartore ,
No worries.  I have also been busy with thesis stuff that just ended a month ago.  Congratulations on getting married!

I have been struggling a bit with what outputs to include in a checklist component.  The reality that I feel we are facing is that each type of energy model usually requires a custom set of outputs depending upon the systems used.  In the current output component, I get around this by just requesting all variables for a bunch of different types of systems and E+ is smart enough to know that there is nothing to output for these variables when the system is not present.  At the moment, I am going to start building out a result reader that can parse the SQL file output by OpenStudio, which should be faster than our current one and should allow greater freedom over picking out certain outputs after a simulation is run.  After I have coded this and learned how this SQL stuff works, I will re-visit the idea of a checklist.

The cooling/heating coil outputs seem like the correct ones and I thank you for finding them.  I am currently thinking that it would probably be best to reserve the Read EP Result component just for zone-level results and so I am thinking about switching the heating/cooling output to be these coil ones that you have stated.  I will do this if I can first get the Chiller/Boiler Energy of the VAV system easily imported with the SQL reader in the next few weeks.

-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

That's great! This new component seems a clever way to avoid the current discrepancies (see the missing cooling energy in the Read EP Result when selecting Packaged VAV as a system). Are you then going to somehow link the SQL result reader with the OpenStudio HVAC System ID, am I right? Looking forward to see your development, I'm sure you'll come up with a "swiss army knife" results reader!

I second your point of view on the current Read EP Result: it's better to keep it on a zone level with a warning that the energy related outputs are shared with all the conditioned zones.

**Comment by chriswmackey** [comment]
@jacoposartore ,

I have finished adding the ability to import energy results for all ASHRAE baseline HVAC types and I realized that importing zone-level heating/cooling loads for centralized systems is really not what is wanted most of the time.  I would much rather have the Read EP Result component bring in the system energy use and the Read EP HVAC Result component bring in the zone-level heating/cooling loads.  Otherwise, it just seems to open the door to people misinterpreting building loads as building energy use.

The SQL abilities turned out to be a lot less exciting than I initially realized and they can take a long time to generate.  For the forseeable future, a CSV-based request of outputs seems to offer the greatest flexibility and power to the user.

So, to close out this issue, I am thinking that I just find a way to bring in the zone-level heating/cooling loads on the Read EP HVAC Result component.  Let me know if you get the chance to try out the new components or you disagree.

-Chris

**Comment by chriswmackey** [comment]
@jacoposartore ,
The original issue has long since been fixed and I have been using the HVAC Result Reader a lot to check detailed information on HVAC systems (especially airflow rates).

As for the desire to read heating/cooling loads of individual spaces, it becomes nearly impossible with centralized systems like VAV to tease out the contributions of individual zones.  At the end of the day, if you are interested in zone-level loads, then you really should be running a simulation with zone-level systems (in particular ideal air loads).  The most recent HVAC components allow you to set the same exact parameters for your ideal loads system as you do for a full HVAC and so I am going to recommend running an ideal air version of your building and HVAC whenever you want to visualize zone-level zones or reconstruct a loads-based energy balance of your building.

Given that this ease of interoperability between ideal air and full HVAC has established along with recommended workflows, I am going to close out this issue.  Please comment if you feel there is more to be done here and I can reopen.

Thank you,
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

I see your point, an ideal air loads system is fine for me as well to visualize every zone's quota of the whole building's heat added or removed, then I'll use each percentage to calculate the specific VAV energy use for the zone.
Thank you,
