### ISSUE TITLE
Change the license to GPLv3

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#335]
All [which includes Ladybug+Honeybee users, developers, and also friends!],

Following [this discussion](http://www.grasshopper3d.com/group/ladybug/forum/topics/acustic-simulations) on Grasshopper group I had a conversation with Arthur and it went pretty well. There are good chances to work together and it will be awesome to finally have aucostic simulation being added to the package.

As part of the conversation he brought up some valid concerns about using creative common license itself and it's incompatability with GPL. that you can read in the links below:
http://creativecommons.org/tag/gpl
https://wiki.creativecommons.org/ShareAlike_compatibility_analysis:_GPL

As the result of all the conversations I think we should change the license to [GPLv3](http://www.gnu.org/licenses/gpl.html). GPL provides what I was originally looking for by choosing the [current license](https://github.com/mostaphaRoudsari/ladybug#licence):
 
```
It means you can copy, distribute and transmit the work or remix it to adapt the work. You can also use it to make commercial use of the work, BUT you must attribute that the work is based on Ladybug, and if you alter, transform, or build upon Ladybug, you may distribute the resulting work only under the same or similar license. This process will ensure that Ladybug and its future versions will stay free and accessible for everyone.
```

SO WHAT?
-------
I think the main question that I need to answer here is what will change for the users and developers by changing the license?
The answer is actually nothing! It is a change to make it easier to collaborate with other open source projects and also use a license that is written in specific for open source software development. [When I read this twice it sounded so marketing to me but this is the reality this time! =) ]

Please let me know your thoughts and suggestions. Specially if you disagree for some reason I really like to hear from you. Otherwise I will change the license on the website and inside the components at some point soon before the next public release.

Cheers-
Mostapha

PS: Sorry @arkdanielnielsen if I forget to include you in the call. It was one of that weeks! Thank you for putting us in touch and I won't forget next time! :beer:

**Comment by arkdanielnielsen** [comment]
No worry, I am just looking forward to do acoustic simulation together with daylight, comfort and energy, and maybe also LCA at some point :)

**Comment by mostaphaRoudsari** [comment]
Hi Danile. I'm actually working on the LCA part too. A collaborative effort with Tortuga  project > https://github.com/moethu/Tortuga/issues/1

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I absolutely agree that we need to move away from the current creative commons licence as it really is not meant for software and does not really provide us with adequate protection against proprietary software that could copy our code.

I also agree that GPL is the type of new licence that we want to be using, which was the licence originally created by Richard Stallman to describe his GNU compiler and all of the wonderful Linux awesomeness that has followed.

To clarify what the key difference between GPL and other Open Source licences is to code-contributors, all open source licences fall mainly into two categories:

1) Licences that allow proprietary software companies to copy the open source code into their own projects and sell the resulting software as a closed-source product (generally referred to as BSD-type licences).  This was the licence given to some of the original manifestations of Unix and I think it is fair to say that this was part of the reason why Unix ended up in such a legal mess.  However, it is also the style of licence that EnergyPlus and a few other notable open source projects use (http://apps1.eere.energy.gov/buildings/energyplus/energyplus_licensing.cfm).  The "upside" is that this licence does allow open source code-contributors to work for proprietary software companies and copy their code into the proprietary project without conflict of interest.  The downside is that it can often lead to proprietary companies taking advantage of open source free labor, simply copying code, not hiring the original coder, and giving no credit or compensation to this original coder.  This situation can be assuaged in some cases, such as the fact that E+ demands a small amount of money when you want to make a commercial derivative of it.

2) Licences that do not allow proprietary software companies to copy the open source code unless the company makes its own software open source (generally referred to as GPL licences).  As the links that Mostapha posted say, this is the licence used by over 50% of the open source community.  It embodies a commitment to open source and includes an implicit "Stallman-esque" ideology that all software should be open source (hence why copying open source code into a proprietary project "infects" the project and makes it open source).  With this comes an alignment with an economic philosophy that we should not develop software in a classic fordist assembly-line "division of labor" where one person writes the base code, another builds an interface for it, another brings it the two together, another markets it, etc., since this linear assembly line needs to have a final software product to sell in order to sustain itself.  Rather, we should use software as service-based craftsmen or artisans, advancing code as demand rises for new applications or projects and being involved in the creation of software all of the way from development off of existing code through the final application of it, to the sharing of the code to foster further development.  So the "downside" of the GPL is that it is in conflict with some aspects of classic division of labor and traditional corporate structure, which does not make it any less economically valid but does mean that it can be difficult to use in these settings.  The upside is that it definitely ensures protection to the code contributors and reinforces a community mentality that we will all benefit most if we share our tools, resources and capabilities with one another.

I hope this clarifies the discussion to others watching the thread.  As stated at the top, I am in agreement with the GPL, its philosophy, and its economics.  I just wanted other code contributors to be informed of the issues behind the licencing decisions.

Stay awesome,
-Chris

**Comment by AvdHarten** [comment]
it seems like this conversation went very productively. I'm glad.

**Comment by mostaphaRoudsari** [comment]
Done and done! ea1b05ec5f040a202b19eb0cf3958af37bf33207 :tada: :balloon: 
Thanks everyone.
