### ISSUE TITLE
Q to the output "mesh" from "Generate Test Points" ?

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#336]
I am wondering why the output "mesh" of the Generate test Points is not offseted together with the points. I suppose the "mesh" should be used for creating the colored analysis mesh later?
![honeybee_daylight_analysismesh-01](https://cloud.githubusercontent.com/assets/7299731/7441754/e5f9ecde-f0f5-11e4-809f-e38ecbb73da2.JPG)

**Comment by chriswmackey** [comment]
This is something that I would like too!

**Comment by mostaphaRoudsari** [comment]
We can have it as an input option but in general there are cases that you don't want to move the mesh. For instance if you run a radiation analysis on couple of external surfaces then move the surfaces out will result in a slightly open geometry.

I agree that the frequent use of the component is for interior surfaces similar to what you showed in this image. I will add the option to the component soon.

**Comment by mostaphaRoudsari** [comment]
Ah! I also rememberd one more case why it is is not there... Think of an sphere or when you have a nonplanar surface. Then where should the surface move to and based on which normal direction?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Given that you implemented this a while back, I am closing out the issue.  I just added one last tweak to what you implemented: I now make sure that the magnitude of the move vector is equal to the distFromBaseSrf:
https://github.com/mostaphaRoudsari/Honeybee/commit/3f9119275dc19c3f3f375293c0db74e8f705785c

This should do it and, if you feel otherwise, please re-open.
-Chris
