### ISSUE TITLE
Bug !? "IntersectMasses"

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#338]
I think there is something wrong with the "IntersectMasses" component. I have tried different methods I found from @chriswmackey - but none of the methods is working. As seen in the image, the two masses is not split, they are still two masses that overlaps each other.
![honeybee_intersectmasses-01](https://cloud.githubusercontent.com/assets/7299731/7443968/db9c2364-f16e-11e4-8d56-f140155efc75.JPG)
The file if that is needed: https://www.dropbox.com/s/9hqvtainze5fa30/Honeybee_IntersectMasses-01.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen intersection is just tricky in general. I will leave this open so we can check it at some point. Meanwhile you need to take care of the operations yourself using Grashopper/Rhino components.

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
The original IntersectMasses component failed in a lot of cases where you had two adjacent zones next to each other and just wanted to get their overlapping surfaces to match (so that you would get correct heat flow across them in the E+ model).  I interpreted this as the primary purpose of this component and re-wrote it to almost never fail in these cases.  This meant that the component was no longer suitable for cases where you had overlapping solids but this seemed ok to me for the following reason:

The type of operation that you are doing in the image seems a bit dangerous as it is unclear how you want to zone your building.  Does the overlapped region become its own zone? Does it just remain two zones and one of the boxes take a chunk out of the other?  If so, which one takes the chunk out of the other?  And if you are also doing core-perimeter zoning, there are a whole set of other zoning issues to resolve.

It just seemed best to let the user decide the zoning themselves and make a component that just helped them turn it into a correct energy model.  Let me know if you agree and we can close the issue.  Otherwise, I guess we could write another component to deal with solid intersections in some way but you will have to be clear about how the zoning should happen in these cases.

-Chris

**Comment by arkdanielnielsen** [comment]
Thanks guys for your replies.
I have not looked at the interest component for a long time, and when I was preparing the webinar I just wanted to show the different components. Actually I never use it, but it could probably be useful in some cases when modeling conceptual models.
@chriswmackey I follow your thoughts about how should the component separate the masses, but maybe it is not so important in the early stage!? Except the case where the masses also are perimeter divided, that creates a lot of unnecessary zones. The use of native component could do it, either union, or split e.g., the only thing is, your need more component to do it. On the plus side you have the control of the dividing.

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen I tend to agree with @chriswmackey's input here. I think if it doesn't really matter for the users then they can use Grasshopper's functionalities to union both masses beforehand.

As Chris (and the spiderman) would say: With great power comes great responsibility!

**Comment by arkdanielnielsen** [comment]
You guys are funny ;)
To the last question. I though the "Solve Adjacencies" solved intersecting surfaces?

**Comment by mostaphaRoudsari** [comment]
Hi @arkdanielnielsen. No, SolveAdjacencies doesn't do intersections. The reason is that it can be pretty computationally expensive to calculate the intersections each time. Sorry for the very late reply.
