### ISSUE TITLE
Read EP Result error with most recent components

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#381]
Hello everyone,

I'm getting a red error (Solution exception:Index) on the Read EP Result component when running EnergyPlus simulations:

![ep error](https://cloud.githubusercontent.com/assets/8501837/10095577/1771f26a-636b-11e5-956c-8e71847d9d18.png)

When using old components from early September everything works fine.

![ep ok](https://cloud.githubusercontent.com/assets/8501837/10095602/35f90a0c-636b-11e5-8ebd-44d1ac1c8d7e.png)

Here are the definitions I used, respectively:
https://www.dropbox.com/s/eyfaq1auc1har09/EP%20Error.gh?dl=0
https://www.dropbox.com/s/hkzr15l6162946g/EP%20OK.gh?dl=0

**Comment by chriswmackey** [comment]
@jacoposartore,

I am pretty sure that this is happening because you did not manually replace the readEPResult component after running the uodate honeybee component. I added a new output for outdoor air energy to allow you to reconstruct the energy balance that E+ is running.  Because of this new output, you need to replace the component manually.

Let me know if this fixes it and, if so, close out the issue.

-Chris

**Comment by jacoposartore** [comment]
thank you @chriswmackey, that solved the problem. I'm closing the issue.
