### ISSUE TITLE
OpenStudio HVAC system 5 

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#400]
@chiensiTB  @chriswmackey 

When I am setting HVAC system 5. I am getting the error that the coolingairflow is not defined in the dictonary HVACdetails, please see the file I sent to you by email. (Cant attach GH files here)

Can I also ask why is System 5 the only system that has this key in the dictionary along with 'heatingAirflow',and 'floatingAirflow'.

**Comment by chriswmackey** [comment]
@antonszilasi ,

This is my fault.  Since we are now assigning these flow rates on the zone level (as opposed to the system level), there is no longer a need for these flow rates in the HVAC dictionary.  I switched this over for the other systems but forgot to do so for system 5.  This is fixed in this commit:
https://github.com/mostaphaRoudsari/Honeybee/commit/cea133d6656f7fed74c065eed4092df4c4ec273a

@chiensiTB was absolutely right that we need to do some general thinking about the issues and organization before doing any implementation of all the systems.  For example right now, there are 3 different places where you assign HVAC availability - on the "Set Zone Schedules" component, the AHU component, and the availability manager.  I know that we put each one of these in for ease of access but it makes it really confusing for the user to not have a consistent way of doing this.  We need to really understand what the best way to do this is before diving into code editing (or at least focus our efforts on making one common system good and then apply that template to the others).

-Chris

**Comment by mostaphaRoudsari** [comment]
```or at least focus our efforts on making one common system good and then apply that template to the others```
:+1:

Having several inputs for the same value is no good. I would consider that as a bug that should be fixed.

**Comment by antonszilasi** [comment]
@chriswmackey ok that solved that one lol, do you understand why only system 5 has 'heatingAirflow' and 'floatingAirflow'

**Comment by chiensiTB** [comment]
Hi @antonszilasi and @chriswmackey .  Thanks for this start to new feedback.  So I agree with you agreeing with me, of course.  Now onto anton's question:

In my component on my own machine, which should be the same as everyone's, I also note that floating airflow and heating airflow has not been coded out fully in all of the system type descriptions.  This is simply because I did not fully work through this use case.  

If we would like to work on use cases where it is possible to override default Autosizing behavior, this would have to be tested for each of the systems types to ensure it is coded properly and works appropriately.  I have never tested this feature up until this point, but I did put the inputs there for future development.

**Comment by chriswmackey** [comment]
@antonszikasi ,

To clarify further, in the last 2 weeks, I was playing around with the implementation that @chiensiTB did of this feature and realized that it was not working for a lot of systems and that, from a user perspective, we should be overriding any autosizing by using the input specifications for outdoor and recirculated air on the zone level (not on the system level as Chien Si initially implemented it). As such, I took chiensi's feature out and replaced it with an override that I tested and I knew worked (at least for system 7).

I think a big reason why your initial implementation did not work @chiensiTB is that you have to size the airflow of all of the components in the system first (air terminal +fan) before you can specify different flow rates for heating, cooling, and floating. As such, I am not focusing on specifying different rates for heating, cooling, and floating right now and just focusing on getting the minimum outdoor and recirculated air to work first correctly first.

-Chris
