### ISSUE TITLE
Open studio ASHRAE HVAC components roadmap 

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#403]
Hi Everyone

@chiensiTB @chriswmackey @mostaphaRoudsari 
Even after our skype meeting the other day and few emails back and forth I am still quite confused as to where we are at and what needs to be implemented with these components. I also wanted to put all the information in one place. This is to help me and hopefully everyone else clarify this. We can discuss all the issues here and then I will put together a wish list and assign tasks to each person. Please reply to each question with question 1.,2. A, B etc

**Key info to date**
1. Find attached Chien Sis excellent outline of the system architecture in the PPT (actually cant attach as don't have write access to this repo, Chris could you attach it for me?)

**Tasks  - Chris and Anton**

As per Chien Si's email:

1. testing out different systems on multiple single zones
2. testing out the same system on multiple single zones (though copies of one another with minor tweaks of the system (for example, two system type 7 with different fan efficiencies and two central plants)
3. same concept as the prior two things, except a collection of zones

**Tasks and questions  - All**

**A.** We talked about upstream zone preparation (setting flow rates) -  *Question 1:* Is this the same component as the task 4? 

*Question 2:*
 @chiensiTB  As per our discussion here   https://github.com/mostaphaRoudsari/Honeybee/issues/400
my understanding is that in System 5 you are able to set flow rates for 'coolingAirflow', 'heatingAirflow' and a bunch of other airflows that are not possible in the other System types because you couldn't work out how to do it in the other system types.

Furthermore do we follow Chris's suggestion here https://github.com/mostaphaRoudsari/Honeybee/issues/400#issuecomment-153367351
to do away with setting flow rates on a system level and set outdoor and recirculated air on the zone level instead? 

If we follow Chris's suggestion can I assign myself to implement all air flow rates on a zone level?
If we keep them at a system level, then can I assign myself to go through the Open Studio SDK to work this out for each SystemType? 

**B.** We talked about adding heat recovery - Question: This would be added to which component? Also this is only applicable to HVAC systems with airloops right?

**C.** Figure out a coherent way to set HVAC Availability, as per 
https://github.com/mostaphaRoudsari/Honeybee/issues/401

**D.** An upstream component for zone preparation. Chien Si thinks this is appropriate although we need to investigate exactly what we intend to do. I am still confused as to why we need this and the value of it @chriswmackey could you elaborate your thoughts on this issue.

**Comment by chiensiTB** [comment]
Hi @antonszilasi.  I see the need for two different paths of development.  One path is the "define airflow rates path".  I don't agree with Chris to do away with system level airflow rates.  I believe @chriswmackey that setting the airflow rate at the air handler sets the airflow rate of the airhandler, and setting the airflow rate at the zone is at the zone level.  For systems that support multi-zone control (VAV, e.g.) this would be an appropriate task.

The task for #400 is two parts.  Ensure that it is possible to set the airflow rate at the system level.  This should override the autosize feature of EnergyPlus at the system level.  Part two, is to also ensure a user may set zone level rates as well.  This is what you call part D in your question.  Chris, I believe has started this component already.  But we should make it possible to do both independently.  This of course raises questions about what to do for systems type 1,2,3,4 which are inherently single zone in nature.  What is the point of setting it twice?  How does open studio respond?  It would have to be investigated.

So my suggestion would be to set up a two part experiment for each system type.  Part one, using expanding the OpenStudio components to accept system level airflow commands, and seeing that this will override Autosize.  Part 2 is setting at the zone level (this is the upstream component for zone preparation).  The point here is to see that zone level is being set appropriately, regardless (independent of) the system level settings (Autosized or not).  This is a fairly large task all things considered.  Does it make sense?  I suggest we hold a meeting today or tomorrow to discuss.  I am more free today.

As for heat recovery.  This would be a new component that would be another input for air handler detail component.  This is a new feature request that I would have to make.

I still owe a coherent explanation for #401.  Sorry, I was exhausted last night and couldn't quite get to it.

**Comment by chriswmackey** [comment]
@chiensiTB  and @antonszilasi 

Thank you for the insight and the visuals in your presentation, @chiensiTB ,will be super-useful for communicating how to others about how to use the components:
https://drive.google.com/file/d/0Bz2PwDvkjovJNG1MU2VFLXVGdUk/view?usp=sharing

I agree with the way that you have organized the components and I should say that, over the last year, this organization has actually helped me better understand how HVAC systems are set up (I have to imagine that this will help other users as well).

I am glad you agree that the minimum outdoor/recirculated ventilation should be set on the zone level.  I agree that all other HVAC inputs should probably be set on the systems level. I was debating for a while about having HVAC availability on the zone level but have decided that our first full implementation of this should get rid of the zone-level input of HVAC availability and we will just focus on the availability manager. This takes care of C.

Since we are assigning outdoor and recirculated air rates at the zone level, I think that it is redundant and confusing to have an additional means of specifying airflow rates on the AHU level.  However, I agree that the economizer, fan, and coil components can keep their ability to override their individual sizing since this allows users extra freedom to set of the sizing of the different parts of the HVAC.  This takes care of A.  @antonszilasi , I think that I should probably finish what I started with implementing this over-riding of sizing if you don't mind and I promise not to delay too much.

In the meantime, @antonszilasi , if you could produce a document that has all of the components in @chiensiTB 's visual but also includes all of the inputs of each component, this would be super useful on helping us nail down a coherent roadmap.  This also means deciding on what inputs are important for a heat recovery component.  This takes care of B and also means that you should think about what variables are important for the plant.

D is no longer an issue since the airflow rates will be set on the "set zone loads" component.
https://github.com/mostaphaRoudsari/Honeybee/issues/396

-Chris

**Comment by chiensiTB** [comment]
@antonszilasi.  I believe an appropriate use case for you to work on in the short term is to either attempt to complete systems 6 and 8.  How is that going?  Or alternatively, you can begin to work with Chris on an upstream zone override component.

@chriswmackey should we meet again this Saturday?  I can bring a features request and bug/enhancement list.

**Comment by chriswmackey** [comment]
@chiensiTB ,

I think meeting this saturday is a good idea. We seem to all be on different pages right now. Since system 5 is also VAV, I think the implementation of it will be easier after I have finished adding in zone-level inputs for system 7 and we have solidified things like the plant details and heat recovery.  Then, implementing system 5 is just a matter of using a lot of the same code from system 7.

-Chris

**Comment by antonszilasi** [comment]
@chrismackey @chiensiTB

Meeting this saturday sounds good. Just give me a time and I'll find a cafe (Travelling again). Chris I think getting me to list the inputs on each component is an excellent idea. Lets make that one of the outcomes of the meeting, therefore questions that spring to my mind for the meeting are.

- Should outdoor and recirculated air be set at a zone level? 
- Should other HVAC inputs be set on the systems level?
- Where should HVAC availability be set? 
- Sorry perhaps I missed something; how do we integrate availability manager into all this?

Any more thoughts on issues to discuss? I will print out Chien Sis component map and dooble on it during the meeting.

**Comment by chriswmackey** [comment]
@chiensiTB and @antonszilasi ,

Let's plan to talk again at 11 AM EST tomorrow unless you state otherwise here.

-Chris

**Comment by antonszilasi** [comment]
Sounds good

**Comment by chiensiTB** [comment]
Great, I will be on skype at that time and ready to go.
