### ISSUE TITLE
isStudyOver fails for Daylighting analysis

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#424]
A couple of users reported this recently. It's not clear if it is an issue with Windows 10 or there is other reasons.

**Comment by mostaphaRoudsari** [comment]
http://www.grasshopper3d.com/forum/topics/hb-annual-daylight-simulation-cannot-find-the-results?groupUrl=ladybug&xg_source=msg_com_gr_forum&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1203169&page=2#comments

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
As you know, I experienced something similar the other day.  However, I was using Widows 8 and the error message from the component was different. I could not re-create the error after that one weird occasion. However, while I have since been able to run the annual analysis, I have not been able to run the Read Annual Result I on either windows 8 or windows 7. The Daysim function that it calls keeps crashing and I have been getting arou dit using the Read Annual Result II.  Perhaps some recent update from Microsoft is causing all of this trouble.  All of these cases are as mysterious as the well-known bug in the DAYSIM function that "Read Annual Result I" calls.  I will focus on documenting this bug as soon as I can.
-Chris
