### ISSUE TITLE
Test points rotated when north changed

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#431]
Hi,
I think there is a bug when changing north direction using daylight simulations.
See this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/an-error-in-honeybee-recolor-mesh/showLastReply
The points are rotated somewhere between the recipe and the analysis component.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham, I replied [here](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1416176). Let me know your thoughts.

**Comment by ayezioro** [comment]
Hi Mostapha,
Thanks.
This is the reply i wrote on the forum, but i have more questions/comments. Probably most of them because ignorance, so sorry if so.
I believe there is something new that i need to learn. getting the rad file/materials imported, where they are supposed to be connected in order to simulate the annual analysis?
Now, supposing i want to parametrize the orientation for annual analysis, what will be the recommended process to do so. Assuming you can get the rad geometry and materials back into a simulation, this rad file is produced by an annual analysis. So you need to do the simulation twice (one for creating the rotated geometry and one for the "real simulation". If so, this will be a killer in the bad meaning of it), since the simulation time can become endless.
A bit confused on this side of the room ...
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham,

After reading your comments, and also a bug report, I changed the approach and the component outputs the original points. You don't need to run the analysis twice. If you run it just once it should work fine.

To make sure there is no confusion I try to explain the current workflow. In all the daylighting simulations except the annual simulation Honeybee just rotates the sky and geometries stay as it is. In case of annual simulation though since there is no easy solution to rotate the sky Honeybee rotates the geometries and test points before running the simulation.

As a user you don't need to know about this until you try to re-create the analysis from the folder. There you will see that the geometries and test points are rotated. I didn't feel this to be a problem and leave it as it is however we can keep track of this too if you think geometries should be rotated back when you import them into Rhino.

![image](https://cloud.githubusercontent.com/assets/2915573/11980915/59e3511a-a96c-11e5-8222-e2b6bb36789d.png)


Hope it helps. Let me know if there is any other questions?

**Comment by mostaphaRoudsari** [comment]
PS: I should have send these links to you in an email but anyways. Check the links below.
https://twitter.com/__Mostapha__/status/674851348597350400
https://twitter.com/__Mostapha__/status/676308602337013760

**Comment by ayezioro** [comment]
This is awsome (The Dynamo views). The shore line is at view.

As for the orientation issue, i'll check later and let you know.

Thanks,
-A.

**Comment by ayezioro** [comment]
Smooooooooth.
Perfect. For now i don't think geometries need to be rotated back.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Great. Thanks for the feedback.
