### ISSUE TITLE
HB_callFromLibrary error

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#434]
Hi,
Being in need of calling radiance material from the library i get the following error in the callFromLibrary component:
1. Solution exception:'dict' object has no attribute 'type'
Checking the errors in the code editor i get:
Traceback:
  line 1093, in searchRadMaterials, "<string>"
  line 70, in main, "<string>"
  line 79, in script

The component is red right after inserting it.
I would say that i'm not updated, but you can tell that i am. Just to be sure i downloaded again the git libraries.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham,

I can't reproduce this issue. Looks like an issue because an old version of Honeybee is flying around.
In the older version Radiance materials were collected as dictionaries and in the new version they are objects. Can you drop a new Honeybee_honeybee to canvas and then re-insert this component?

In any case version check should have warned you about this. Let me know if my guess is right and we can solve the version check issue after that.

**Comment by ayezioro** [comment]
Hi Mostapha,
Tried it but no results.
Now itried opening a new session of rhino+GH and it works.
I noticed that when you remains with R+GH open for a few days they get tired and behaves weirdly. For instance this case.
You can get crazy with such things.
Thanks. I'm closing the issue.
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks! Let me know if it happened again and I can take a closer look. The new version always should overwrite the material library. Maybe I'm making a mistake somewhere in the process.

**Comment by ayezioro** [comment]
Oh no!! Its not you!!
I noticed strange behaviors some other times after i left R+GH open for quite a long time and many files opened.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I also notice such behavior usually occurring for the reason that @mostaphaRoudsari cites: if you open up a GH file with an older version of HB_HB, your other open GH files will try to call functions from this older HB_HB since only one HB_HB can be flying at a given time.  I usually solve the issue by re-computing the canvass that I am interested in so that the HB_HB on that canvass is loaded into the memory.
Let me know if I am making sense.
-Chris

**Comment by ayezioro** [comment]
Thanks Chris,
Definitely makes sense!! I was in the process of updating old files when it happened.
Thanks for the tip.
-A.
