### ISSUE TITLE
Suggestion for the IES component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#453]
@sariths I just downloaded the example file from Hydra. It looks very great and it's easy to follow. I just have a suggestion for outputting the data as a class instead of a list of a dictionary. You will need to modify how the other component reads the values which should be pretty straight forward. I think it will look much nicer and will be human readable.
![image](https://cloud.githubusercontent.com/assets/2915573/12189400/34840452-b58b-11e5-9545-db508561ec73.png)

[Here](https://www.dropbox.com/s/vzt93hypeklj1te/IES_indoor_Electric_Lighting.gh?dl=0) is the modified file that has the alternative component. I also added some results visualization to the file. I suggest to use Rhino preview as the thumbnail for Hydra instead of the Grasshopper definition.
![image](https://cloud.githubusercontent.com/assets/2915573/12189488/3030ecfc-b58c-11e5-8952-cc19defa9977.png)

I also removed some of the default folders that you had in grasshopper definition (e.g. g:\someFolder). This way we make sure that it doesn't give an error on systems with no G drive.

Finally you need to save the grasshopper file right before creating a Hydra to make sure it will export the latest version of your file. The example on the Hydra is missing couple of last steps. It might be a good idea to use the new file to update the example file on Hydra.

**Comment by sariths** [comment]
Hi @mostaphaRoudsari , 

This *"suggestion for outputting the data as a class instead of a list of a dictionary."* is done. See below:
![1-7-2016 11-19-07 pm](https://cloud.githubusercontent.com/assets/10361848/12190330/4b82ded0-b595-11e5-9258-71eae5e1617b.jpg)
I was putting stuff inside lists before because I couldn't think of a better way of doing this. 

I need to make a few additional changes (one bug and few improvements) before I send you a new pull request. I think I will send you a new pull request with all the changes by tomorrow or Sunday.

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by mostaphaRoudsari** [comment]
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1438108&xg_source=msg
