### ISSUE TITLE
Error "Red_EP result, get surface color & doesn't  correctly Run EP 

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#461]
Hi 
I used  that latest version (LB 0.0.62 & HB 0.0.59) of this component (Jan_26_2016) returns this error:

Runtime error (TypeErrorException): unsupported operand type(s) for //: 'float' and 'NoneType'
Traceback:
  line 389, in getData, "<string>"
  line 698, in script

and

Runtime error (MissingMemberException): 'str' object has no attribute 'GetBoundingBox'
Traceback:
  line 664, in script

TNX

_Omidmr

#Honeybee #EnergyPlus

**Comment by chriswmackey** [comment]
@Omidmr ,
Thank you for reporting this. I believe that it results from a recent change that we made with graphic standards for the components.  I will take a look at it shortly and attempt to fix it.
If you could post a link to a GH file that shows the error, it would help me fix it sooner.
Thanks again,
-Chris

**Comment by Omidmr** [comment]
YW, TNX T U.
https://www.dropbox.com/s/fvzo5lzm4oasnfs/OmidTest.zip?dl=0

**Comment by Omidmr** [comment]
And this file has multiple zoning.
https://www.dropbox.com/s/gziinw0a0hvpzzp/Omid_2nd_test.rar?dl=0
TNX
-omid

**Comment by chriswmackey** [comment]
@Omidmr ,
The error in color zone surfaces was occurring because one of the zones did not have any floor surfaces and it was trying to normalize by floor area.  That bug has been fixed.

The error in "Read EP Srf Result" was happening because of curved surfaces and I have since put in a check that fixes this case.
![coolhousegeo](https://cloud.githubusercontent.com/assets/5567574/12572146/585c1a52-c3b6-11e5-8d41-fe67c87e7ae7.JPG)
Your working example file can be found here:
https://www.dropbox.com/s/nczx83d953oq0yh/OmidTest%2BCWM.gh?dl=0

The curved surfaces were also the reason why the simulation took so long to run and I would recommend planarizing the geometry if you will be testing multiple iterations.

-Chris

**Comment by Omidmr** [comment]
@chriswmackey 
TNX a lot Chris.
Did you check First file?. That file has a multiple zone.
https://www.dropbox.com/s/gziinw0a0hvpzzp/Omid_2nd_test.rar?dl=0
Thanks again,
-Omid

**Comment by Omidmr** [comment]
@chriswmackey 
TNX a lot.
-Omid
