### ISSUE TITLE
Errors in run EP & custom EP materials 

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#463]
Hi again,
I try for run EP in ladybug and honeybee that latest version (LB 0.0.62 & HB 0.0.59) of this component (Jan_26_2016) returns show  this errors with custom EP materials:
 
Runtime error (MissingMemberException): 'NoneType' object has no attribute 'GetBoundingBox'
Traceback:
  line 117, in copyHBZoneData, "<string>"
  line 656, in script

and

Runtime error (MissingMemberException): 'NoneType' object has no attribute 'GetBoundingBox'
Traceback:
  line 118, in copyHBZoneData, "<string>"
  line 657, in script

![fgh](https://cloud.githubusercontent.com/assets/11173265/12596443/32efcac2-c495-11e5-8d88-95acc9c69660.PNG)

https://www.dropbox.com/s/nafwmraif5cgsb1/newZoningPHASE1edit002_custom_epmaterial001.rar?dl=0

TNX a lot.
-Omid

**Comment by Omidmr** [comment]
[Error.txt](https://github.com/mostaphaRoudsari/Honeybee/files/105864/Error.txt)

**Comment by chriswmackey** [comment]
@Omidmr ,
You have to give us files that show only what is needed to re-create error.  I can't tell what your issue is  as your file is very large. Your components in your image are red bcause there is no zoneData going into the component. I can also say is that you are creating duplicate materials with the same name and you should just create the material once and use the name of that material to assign it to other constructions.
-Chris
