### ISSUE TITLE
ScheduleTypeLimits=Any Number

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#464]
Hi,
I started to get the following error in E+ simulation:
1. The simulation has not run correctly because of this severe error: 
   ** Severe  ** IP: IDF line~154 Invalid Number in Numeric Field#1 (Lower Limit Value), value=SCHEDULETYPELIMITS, in SCHEDULETYPELIMITS=ANY NUMBER
The file was OK until recently, so i assume something has changes lately.
************************
Checking the idf i see that this type schedule is showing a bad definition (from a text editor):
ScheduleTypeLimits,
  ANY NUMBER,   !- name
  ScheduleTypeLimits,   !- 
  Control Type,   !- - Name
  0,   !- - Lower Limit Value {BasedOnField A3}
  4,   !- - Upper Limit Value {BasedOnField A3}
  DISCRETE;   !- - Numeric Type
***********************
As you see, one schedule definition is in the middle of the other, causing, then, the error.
-A.

**Comment by ayezioro** [comment]
Weird,
I don't know what exactly i did but the files in question are working now. Probably a "recompute" did the trick ...
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
This just happened to me today.  It seems to only affect Honeybee files that have been updated with the "Update Honeybee" component since I was able to build the same file from scratch and everything worked fine.
Recomputing did not work for me when the error came and it really required a brand new GH file. I don't know what update caused it but hopefully we won't experience it if we just work from new components going forward.
-Chris

**Comment by mostaphaRoudsari** [comment]
This is happening because the old parser is parsing this specific schedule in the new library wrong (as you can see in @ayezioro's post).

When you open an old file it will load the library and will overwrite the current library (This was a bug which we fixed later). Now you update the file and Honeybee_honeybee will re_run but it won't overwrite the already loaded objects - since we told it not to do to avoid overwriting any user-defined materials or constructions. That's why it will create the error.
For now the only solution is to close Grasshopper and Rhino and load the file again or we can add a separate check in Honeybee_honeybee to overwrite this schedule to make sure we avoid this issue.

**Comment by mostaphaRoudsari** [comment]
Should be fixed now!

**Comment by ayezioro** [comment]
Thanks,
Will report if it happens again. Hopefully not.
-A.

**Comment by chriswmackey** [comment]
Thanks @mostaphaRoudsari !
It's good to know that this won't affect the updating of the example files now.
