### ISSUE TITLE
openstudio and epw files

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#465]
I want to retake this development:
https://github.com/mostaphaRoudsari/Honeybee/issues/273

The think is that i noticed now that the OS component doesn't like my local epw file. It complains about the following:
**********************************
Current working directory is set to:  c:\ladybug\unnamed\OpenStudio
Runtime error (ApplicationException): Optional not initialized
Traceback:
  line 213, in addDesignDays, "<string>"
  line 2693, in main, "<string>"
  line 2841, in script
**********************************
Connecting others (US for example, runs fine). Previous version of OS used to work (about July 2015).
I can continue dealing with the development but will be nice to get this fixed.
Thanks,
-A.

**Comment by jasbour** [comment]
Hi there,
i am having this issue with OpenStudio,
i want to use it because i want to include radiators for a heating system in my simulations,
but i get this error (as in snapshot),
Is there a workaround that i am missing?
I tried with US weather file and the problem was not solved,
any ideas? Thanks
![osbug](https://cloud.githubusercontent.com/assets/17048234/12786618/3019070c-ca92-11e5-879b-0bd172e0b292.jpg)

**Comment by mostaphaRoudsari** [comment]
The error is because the component cannot find the .ddy file next to the epw file. The solution is to use energySimPar_ and set the path to ddy file:
![image](https://cloud.githubusercontent.com/assets/2915573/12788368/31c73e32-ca67-11e5-829b-970f929cc314.png)

I added a meaningful error message for this case.
![image](https://cloud.githubusercontent.com/assets/2915573/12788878/6fa9001c-ca69-11e5-9121-3cadd58c719b.png)

Thanks for reporting.

**Comment by jasbour** [comment]
You are so fast and helpful!
that was the issue,
still i am now getting this error, which must be associated with my schedules,
because when i disconnect them, its working, but it's not working when i connect them,
they are custom made, 8760 values, inputted in the "Set EnergyPlus Zone Schedules" component,
am i doing something wrong? this is a snapshot,
thank you
![schedules_prob_maybe](https://cloud.githubusercontent.com/assets/17048234/12791047/9b13541e-caa5-11e5-83e0-fee40e7bf28f.jpg)

**Comment by mostaphaRoudsari** [comment]
@jasbour - @chriswmackey should be able to help you with this one if you open a new issue. He has already fixed it once: https://github.com/mostaphaRoudsari/Honeybee/issues/455

**Comment by jasbour** [comment]
ok
thank you
