### ISSUE TITLE
Honeybee generation Always On schedule not being written to IDF by default

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#512]
@mostaphaRoudsari, it seems that the Always On schedule is not being written to the IDF please see: http://www.grasshopper3d.com/group/ladybug/forum/topics/honeybee-generation-is-ready-to-fly-example-work-flow?commentId=2985220%3AComment%3A1539547&groupId=2985220%3AGroup%3A658987 

I thought it was written by default, I fixed this issue by writing it manually any ideas on what is happening here? Please follow up on my other issue here when you can too, thanks! https://github.com/mostaphaRoudsari/Honeybee/issues/487

**Comment by mostaphaRoudsari** [comment]
@antonszilasi thank you for reporting this. If I remember right we had this issue before in OpenStudio component that @chriswmackey has resolved. I won't be able to check it today but will try to check both of the issues tomorrow.

**Comment by chriswmackey** [comment]
@antonszilasi ,

You are correct in that the "Always On" schedule is not written into the IDF by default but it is incorrect to label this as a bug as it has been intentional up until this point.  While I thought about adding in the ALWAYS ON schedule regardless of whether it is specified by any EnergyPlus objects (since it's used as a default for so many objects), I had decided to stick to @mostaphaRoudsari 's original code, which only writes in schedules if they are specified by EnergyPlus Objects.  In other words, for each EnergyPlus object, there is a check of what schedule is assigned and, if the schedule is not in the EPScheduleCollection list, it is appended to it.  Them in section [6 of 8], all of the schedules are written into the IDF.

I am of the opinion that this philosophy of only writing schedules if they are called by objects ultimately creates lighter IDF files, although I guess that it would not be such a big deal to add just one exception for "Always On".  Let me know if you feel otherwise but, if you agree with me, then you should put a check in the generator script, @antonszilasi , that checks whether the schedule is in in the EPScheduleCollection  list.

-Chris

**Comment by antonszilasi** [comment]
@chriswmackey I agree and I will put a check in the generator script

**Comment by mostaphaRoudsari** [comment]
Fixed via https://github.com/mostaphaRoudsari/Honeybee/commit/0cb8c11ec49cc694b6f2bdad874e27e3f4966ba8
