### ISSUE TITLE
Honybee shade generator results : Compare with EP and OS (without DDY)

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#534]
Hi @chriswmackey ,
Thanks for check and fix the sizing of the OS.
OS run Fine with custom EPW.
Here is the result of comparation with EP and OS. with shade, without shade, HB context (no shade).
I think the reason of the difference in results of analysis when we using shade as context, EP dosen't calculate account for the surface temperatures of the blinds (EP assume like as tree and also detached object from building) and also we can't set material of the blinds.
I think the result is not accurate for EP.
![compare0](https://cloud.githubusercontent.com/assets/11173265/16896544/3b10c67c-4bac-11e6-8c05-6970d029f3b1.png)
![compare](https://cloud.githubusercontent.com/assets/11173265/16896716/37224bf4-4bb0-11e6-9e8b-14d1c8789c4c.png)
![12](https://cloud.githubusercontent.com/assets/11173265/16897266/35f2c8e2-4bc1-11e6-911e-79ef05f2735d.png)

Thanks again.
-Omid

**Comment by Omidmr** [comment]
@chriswmackey ,
You can find that file in Here.
https://www.dropbox.com/s/18jz2trzonp1xnt/EP_and_OS%20NO%20DDY%20OMD.gh?dl=0

OS component doesn't have capability for run in background like as EP component.
That capability for optimization process very useful.
Thanks
-Omid

**Comment by chriswmackey** [comment]
@Omidir ,

You are correct that surface temperatures are NOT calculated with HB context but this assumption is fine for large shades like overhangs and single fins. In fact, using HB context to account for these large shades is much more accurate than using the EPBlinds material because the context will do a better job of modeling solar distribution accurately (the EPblind material uses a generalization of solar distribution to run more quickly and this is really only applicable to cases with lots of little shades).  If you have a lot of little shades like louvers that are really close to the building, it is more accurate to model them as an EP blind object since the regularity of the shade pattern means solar distribution calculation can be simplified and it becomes more important to account for surface temperature of these objects. You understandably get large differences between the two ways of modelling  because one is usually correct for a given case while the other is not. Let me know if this is clear.

-Chris

**Comment by Omidmr** [comment]
@chriswmackey ,
Many thanks to clarify between two crucial differences.
Finally, we couldn't set materials and layers (such as insulation layer, green roof and etc) to these objects (sidefins, overhang) like DesignBuilder and also TRNSYS, to analysis thermal performance of shade material.

Thanks,
-Omid

**Comment by chriswmackey** [comment]
@Omidmr ,

Adding insulation to fins or overhangs that lie outside of the envelope of the building will not have a significant effect on the building's thermodynamics.  However, if you have shades or blinds that are covering a significant portion of a window, then you might start to see some change from increasing their insulation value.  This is why, for the former, you do not need to define a material or R-Value and you can just use the HBContext.  For the latter, you define a shades material with a certain conductivity and thickness in order to account for any effects from the R-Value.

You can model a green roof or wall in Honeybee by writing a custom material for it as you see in this example file:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Green_Roof_In_Energy_Model&slide=0&scale=1&offset=0,0

There is no way to account for a vegetation that covers in window or a shade in EnergyPlus (only an object to account for green roofs and walls) and so I am assuming that shades with vegetation is not what you meant by what is available in DesignBuilder.

-Chris
