### ISSUE TITLE
Honeybee can't find OpenStudio?

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/honeybee#548]
Hi @mostaphaRoudsari and @chriswmackey , 
Someone raised this [question](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1584088) as a part of another question. I have no idea about the OpenStudio part of the HB interface so I thought I should let you guys know...

**Comment by chriswmackey** [comment]
@sariths ,

The reason why this has come up is because I put in a check for OpenStudio installation in HB_HB that replaced the check for EnergyPlus (since we are officially supporting OpenStudio now and people already get EnergyPlus when they install OpenStudio). It's the same type of check that people get if they don't have Radiance installed.

**Comment by sariths** [comment]
@chriswmackey Makes sense, thanks. Actually, the fact that OpenStudio ships perl along with it is turning out to be really useful for the new Radiance workflows that we are trying out for HB-core.

**Comment by chriswmackey** [comment]
Indeed, there are a lot of great things that come with OpenStudio (including Radiance). At some point in the future, I think we might just have people install OpenStudio to get almost everything that LB and HB rely on.

**Comment by Hk632062562** [comment]
Hi there I just downloaded openstudio2.1.0  at C:\ and HB 0.061. I also tried to install it at C:\Programfile

but the same happened, i took some screen shot in this post i made:
http://www.grasshopper3d.com/forum/topics/error-honey-cannot-find-openstudio?commentId=2985220%3AComment%3A1735388&xg_source=msg_com_forum

If you know how can i fix  it? please i need it urgently to  be use. Thanks in advance

**Comment by chriswmackey** [comment]
@Hk632062562 ,
OpenStudio 2.1 just came out a week and a half ago and I only just added support for it in Honeybee this past weekend:
https://github.com/mostaphaRoudsari/honeybee/commit/8748a4b6b9f52c11e37de4941b3e40813324f2cb
Update your components as it says in the GH Group discussion and all should work.

**Comment by ayezioro** [comment]
Hi,
I've just installed OpenStudio2.2 and i get the warning that it can't find OS.
I installed it at Program Files folder.
Checking the HB_HB code i see that it can be installed either at default location (C:\) or Program Files.
So looking a bit further (line 9225), it says: 

> installedOPS1 = [f for f in os.listdir("C:\\Program Files") if f.startswith("**O**pen**S**tudio")]

This is the problem, having O and S capital.
Changing to:

> installedOPS1 = [f for f in os.listdir("C:\\Program Files") if f.startswith("**o**pen**s**tudio")]

solves the problem, which BTW is what is written in the following line (9226).

Hope this will help to understand why there are many people complaining about this issue.

If i'm here, i also suggest to update the links on the Installation Instructions page (it links to OS 1.12)

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey this has been a constant issue on the forum. I re-open this so we can get it fixed before the release.

**Comment by chriswmackey** [comment]
@ayezioro ,

Your proposed change is not the best way to solve the issue and it is important to stress that OpenStudio 2.x needs to run out of the root of the machine (the C:\ drive).  If you always install OpenStudio in its default location, you will never have any issues.  So just install OpenStudio 2 and above in the root of the machine and install OpenStudio 1 in Program Files.  If you do this, you will find there's no need to edit any Honeybee code.

@mostaphaRoudsari , the reason why this has been a recurring issue on the forums is that we have not done a stable release in a while.  So people are using the old Honeybee components from that last release (that run with OpenStudio 1) with OpenStudio 2.  Because NREL changed the default location where OpenStudio installs, it has created a lot of confusion.  Once we do a stable release and all of Honeybee is officially running on OS 2, these issues will go away.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks for the clarification.

**Comment by ayezioro** [comment]
Thanks @chriswmackey for the clarification.
