### ISSUE TITLE
No SI/Imperial units option on the writeTHERM component

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/honeybee#550]
Why is it that there is only an option to use Imperial/SI on the readTHERM component and not on the writeTHERM component. Is this a mistake? What is the rationale behind this?

We have developed a script for our UK office but be would like to make it available to our US offices.

Thank so much for your time,

Ben

**Comment by chriswmackey** [comment]
I tried my best to make the components able to accommodate all units systems.  Your Rhino model can be in IP units (ie. inches or feet) and you can import the results as IP units (degrees F and BTU/hr).  Are you saying that you need the exported THERM file to be in IP units as well?  As a US citizen, I can tell you many scientific people who are actually working with the calculation engines prefer to have everything in SI and just convert to IP to communicate with clients or to take in drawings from the architect.  Still, I can add it if you think it would help a lot of people.

Adding in the extra capability to make the THEM file IP will take some time.  Let me see what I can do.

**Comment by benmo1** [comment]
Ah excellent, if people in the states tend to use SI then that's fine. We'll have a chat with the offices and see what the normal thing is for them personally, if it varies across the field. I was trying to ask this more as a question. If it is intentional as this is needed then that is also good to know. I thought it might have been an oversight.

**Comment by benmo1** [comment]
Ah sorry I meant rationale not rational!

**Comment by chriswmackey** [comment]
@benmo1 ,

From my perspective, the IP / SI change is happening in the US but it's a more complex, slower (and perhaps more painful :) transition than I feel a lot of other countries have had.  Many hardcore scientific teams in the US work only in SI.  For example, all of EnergyPlus is written in SI and the heart of the THERM engine is also written in SI.  Still, all of the US architectural projects that I know use IP units (feet and inches) and most US architectural clients do not know the Celsius scale.  In spite of this, there's a lot of SI literacy in US architectural offices, particularly in the younger generation and in offices that do international projects.  If you talk to the members of your US office, I would be curious to see what you find.  I know that they will definitely want support to make Rhino/GH Therm polygons in inches and to display results in Fahrenheit but whether they would like the THERM file in IP might be more of a toss-up.

As for intentional/unintentional, the fact that the THERM file is currently in SI was intentional but it was for my personal sanity at the time of bringing all of the software components together.  There's no reason why we couldn't add in the capability if I see there's demand for it.

-Chris

**Comment by chriswmackey** [comment]
@benmo1 ,

I was considering adding in an extra input to the Write THERM component for this but I have realized that there's nothing stopping people right now from working pretty much fully within IP (both within Rhino and within THERM). First, there's no reason to write polygons into the THERM XML using inches because, as long as people in THERM have the IP toggle switched, everything will display and run in THERM using IP units (regardless of the units system in the THERM XML file).

Moreover, THERM seems to have standardized the writing of results into XML files in SI format, meaning that the toggle for SI/IP really does belong on the result reader (as it is now) rather than the Write THERM component.

Finally, I'll say that the Honeybee components are able to translate Rhino geometry in inches correctly into THERM right now so, as long as people set their Rhino units in inches , they can pretty much remain fully within IP as they build their model.  The only areas where users might have to engage with SI is when they input temperatures and film coefficients for the BCs but we have some extra converter components in Ladybug to help with this:
https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/F2C.html
https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/uIP2uSI.html

Given all of this, I'm going to close out this issue but let me know if you feel there's still more to be done here.
-Chris
