### ISSUE TITLE
viewFactor component: allow saving viewFactorInfo and viewFactorMesh

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/honeybee#575]
This is usually the most computational intensive step of the thermal comfort map process. 

It would be nice if we could save the resulting view factors in some way to be used later on. I've had multiple crashes of the definition only to need restarting the viewFactor calculation.

I hope this isn't already implemented and I lost it some place.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
@TheodoreGalanos ,

You have told me in a chat that you already found the "Ladybug_Surface View Analysis" component, which might take care of part of the issue (if all that you need is the numeric surface view factors).  However, it sounds like you need all of the viewFactorInfo (if you want to be able to run the comfort maps).  This is very difficult because there is a lot more information that is being passed in the viewFactorInfo list other than simple view factors (there are literally 20-30 properties that I am pulling off of the zones that have relevance to the comfort maps).  The ability to save or internalize this info would require a full revision of the component.  As a result, it is going to have to wait until the new Honeybee revision, where I will make this viewFactorInfo a special object, which can be saved/written to a text file using python's cpickle module. Let's keep the issue open until I write it into the new Honeybee.

-Chris

**Comment by TheodoreGalanos** [comment]
Hi @chriswmackey 

Thanks for your response. It is not really a priority so no worries. It's just nice to be able to do it in the future. Thanks also for giving details on how you plan to do it, I'll try and go over that module for educational purposes.

May I ask, is calculating numeric surface view factor calculation a big part of the total viewFactorInfo calculation time? I was thinking, but I am really not sure if it is possible to do without a big change, that an intermediate step could be to be able to plug in the numeric values (created and saved by the surface View Analysis at some point) into the view factor component.

Hope I'm not talking jibberish lol.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
Theodore,

View factor calculation is almost all of the runtime of the component (the readMe gives a breakdown). It's still difficult to implement the ability to plug values in but I guess it is easier than the alternative. I'll think about whether it's worth it in comparison to the implementation on the revision.

-Chris

**Comment by TheodoreGalanos** [comment]
Ok Chris,

It's no problem, as I said not a big priority everything works just fine as it is

**Comment by chriswmackey** [comment]
@TheodoreGalanos ,
You can now save viewFactorInfo to a file using the Load/Dump HBObjects component.  This should save you from running this time intensive step more than once.
