### ISSUE TITLE
Question: Ladybug analysis tools Honeybee +ready to fly?

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#580]
@mostaphaRoudsari 

Hi Mostapha, I would like to create a Grasshopper component which only writes the geometry of a OpenStudio model. All the non-geometric attributes will then be applied to the osm using measures.

 Is Honeybee+ ready to fly for this? If not is there something I can do to help sped it along?

**Comment by mostaphaRoudsari** [comment]
Honeybee+ currently imports idf files but doesn't write an idf file but it is an easy method to add. If you're interested to give it a try you need to implement toEPString methods in the level of HBSurface and HBZone.

Check how the toRadString method is implemented, and follow the same pattern for toEPString:
https://github.com/ladybug-analysis-tools/honeybee/blob/master/honeybee/hbsurface.py

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  I would like to write an OpenStudio file not an idf I believe that I need to port all the code in the currrent export to OpenStudio component across and make a new component to put here: https://github.com/ladybug-analysis-tools/honeybee-plus/tree/master/plugin/grasshopper/userObjects

Is that correct?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I remeber that we had a discussion about this at one point but I can't remeber the outcome. Did we decide that we would have a toOsObj function that accepts the model as an input instead of (or in addition to) a toEpString function?

Also, I know that you're on vacation now so there's certainly no rush to respond.

-Chris

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 

If I dont hear from you I will implement a OSObj function and proceed with porting the export to OS component over

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, there is a major API design issue to implement `toOsObjects`.  OpenStudio objects can only be created under a `Model` object which means to get the OpenStudio string for a surface one needs to initiate an OpenStudio model first, add a zone to a the model, add the surface to the zone and then get the whole model together. Maybe there is a way not to do this but since every OS object needs a unique UUID, rather than a name, which will be used by other objects I don't think there is a way to generate the string without creating the model.

@antonszilasi you should just use the current honeybee and comment out parts of the code that are adding any attribute more than the geometry. At this point Honeybee[+] won't be helpful for what you're trying to achieve.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  Ok if you think that the best way to go about things then thats what I'll do. However where does this leave Honeybee +? When can we expect to use OpenStudio with it?

**Comment by mostaphaRoudsari** [comment]
@antonszilasi the energyplus/openstudio integration is not implemented to Honeybee[+] so I still don't know. As I mentioned we first need to figure out how to address the API design issue before implementing it to honeybee[+]. In any case I think your case is much easier to address if you use the current honeybee implementation.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  thanks. A few more questions however, I managed to get the Honeybee+ example file working by loading the modules in using the load_source import methods. See:

![load source](https://cloud.githubusercontent.com/assets/8773483/21503260/b65e7bcc-cc1b-11e6-87a1-0dae046c48c3.JPG)

I realize that this is not the correct way to point python to the modules and instead there should actually be an installer. Have you written one? How would you go about writing one?

One more question, what is the best way to go about debugging code in external libraries? I'm a bit lost on how to debug code that is being called from external libraries.

Thanks
