### ISSUE TITLE
Honeybee thinks raw grasshopper breps are Honeybee zones

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#582]
@chriswmackey  @mostaphaRoudsari 

I am getting some very strange behavior from a raw Grasshopper brep. Honeybee thinks that this brep is a Honeybee zone **before** it has been passed into the Honeybee mass component see:

![honeybee id from raw object](https://cloud.githubusercontent.com/assets/8773483/21205844/09f7b160-c224-11e6-8ca8-db6489700ac7.JPG)

I am guessing that it is picking up on the HB.ID of a previous component that was created, however when I recompute I still have the same issue.

Any thoughts before I start pulling everything apart to work out whats going on?

**Comment by antonszilasi** [comment]
an update here, this happens when I unload and reload Grasshopper

**Comment by mostaphaRoudsari** [comment]
Regardless of why this is happening how does this make an error? Once you create a new honeybee object this will work just fine.

My guess is that you have internalized Breps which used to be HBObjects and since you haven't closed both Rhino and Grasshopper the ID still matches the objects ID in sticky. If you close both Grasshopper and Rhino this will be reset. In any case this is just working as expected and I can't see why this can be an issue of any sorts?

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  ok good to know, you are right its not going to cause chaos! So let's just close the issue.
