### ISSUE TITLE
readTHERM - meshValues vs mesh faces (wish)

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#584]
Hi,
Trying to define my own title for a THERM simulation i've noticed that the number of values is different than the number of faces. Being so, i can't use the reColorMesh component to give my own title ... or even bake the results as with other simulations.
My wish, if what i described is correct, is to fit the mesh and the results as in other simulation types.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

You bring up a good point here.  The mesh that THERM generates to perform the finite element heat flow simulation is not structured in the same way that our other meshes are in LB+HB.  Notably, each vertex of a THERM mesh has its own color while each face of a LB+HB mesh has its own color.  This is the reason why the recolor mesh component does not work with the THERM meshes.

I can think of two ways of dealing with this:
1) I add the ability to customize the title on the read THERM result component.
2) I add some intelligence into the recolor mesh component so that it checks first whether the input data length matches the number of faces and, if not, it checks to see if it matches the number of vertices. 

Personally, I am partial to the latter as this will allow the freedom of converting units and editing the data before plugging it in to color the mesh.  Let me know your thoughts, @ayezioro , and I will implement it.

-Chris

**Comment by ayezioro** [comment]
Thanks Chris,
Option 2 is the preferable one since it will align with the standards of LB+HB.
Is not only the title issue but also the whole other possibilities the recolorMesh enables. So, it is not "urgent". Whenever it comes it will be welcomed.
Thanks again,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I just added this capability to the recolor mesh component:
https://github.com/mostaphaRoudsari/ladybug/commit/eaae3ae1b3dac9e0c5b645054a5fdf21d0c562cc
![recolorthermmesh](https://cloud.githubusercontent.com/assets/5567574/21583805/4c43ed3e-d05e-11e6-89e0-716d430b63fb.JPG)

You can find a file showing how to use it with the THERM meshes here:
https://www.dropbox.com/s/rz9vzjm69a707s4/ThermExportWorkflow.gh?dl=0

This also means that you can now use Recolor Mesh with the colored sky visualizer and the cala lilly too.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey this is pretty cool! Opens up new possibilities.

**Comment by ayezioro** [comment]
This is great Chris!!
Thanks,
-A.

**Comment by chriswmackey** [comment]
Glad that you guys like it.  There are a few other small visualization capabilities that I wanted add before the next release. Stay tuned!

**Comment by chriswmackey** [comment]
@ayezioro ,

I will give the Rhino 6 a try once I get the chance.  I am using a lot of Rhino's geometry functions to help clean up the inputs so it does not surprise me that there might be some new issues.  I have integration with the new THERM CLI at the top of my list and this is the next one in terms of THERM support.

Also, check out what we can do with the new contour component:
![contourthermmeshes](https://cloud.githubusercontent.com/assets/5567574/21600112/3bb6ea56-d145-11e6-8377-0167656f9785.JPG)


-Chris

**Comment by ayezioro** [comment]
This is not good ... this is VERY good!!!
-A.

**Comment by ayezioro** [comment]
A small bug report.
Choosing option 2 for _contourType_ (labeled lines) gives you the following error if no legendPar is provided:
Runtime error (ValueErrorException): max() arg is an empty sequence
Traceback:
  line 2679, in gradientColor, "<string>"
  line 176, in main, "<string>"
  line 369, in script
-A.

**Comment by chriswmackey** [comment]
Thank you @ayezioro , the great catcher of bugs!
It is fixed:
https://github.com/mostaphaRoudsari/ladybug/commit/5145e6854fd6026a7e544505f3c7e1c60f7b0e43
