### ISSUE TITLE
Unreadable code line in EPConstruction component

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/honeybee#589]
@mostaphaRoudsari @chriswmackey 

I have to convert your code in the EP construction component to the enhancement I am working on at https://github.com/mostaphaRoudsari/Honeybee/issues/398

line 123 in this component is unreadable to me, I understand what exec does but I can't understand what:

`exec('materialName = ' + layerName)`

is doing furthermore I can't replicate it in my own code. Can you write this in a different way so I can port it over?

While we are doing this I might as well write it properly so that we can easily move the EPConstruction component over to https://github.com/ladybug-analysis-tools/honeybee

**Comment by mostaphaRoudsari** [comment]
@antonszilasi can you help me to understand why do you need to make any changes to the component to address #398?

To answer your question the code is trying to get the value for each input of the component. The number of inputs for this component and hence the number of input variables in GHPython can change dynamically. For instance if you have two layers, variables will be `_layer_1_` and `_layer_2_` but there is only one layer then you will only have `_layer_1_`.
Since there is no easy way to get the variable itself, I'm using `exec` to get them from a string. The line will be interpreted as `materialName = _layer_1_`, `materialName = _layer_2_` and so on.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 

I am not making changes to the EP construction component, I simply trying to move the pieces of code that put together the EP construction definitions, so that the line of code:

`added, materialName = hb_EPMaterialAUX.addEPConstructionToLib(materialName, overwrite = True)` 

Can place the constructions in the Honeybee Hive

**Comment by mostaphaRoudsari** [comment]
@antonszilasi all the constructions and materials from OpenStudio library has been already added to Honeybee. It's not under hive but you can access them by name. Can you share a little bit more of what are you currently trying to do? You just need to do something similar to setEPConstruction component. Take a look how does Honeybee updates the construction based on surface type. That should give you a better idea of how to call the constructions.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 

Thanks that was foolish of me I didn't check to see if the OpenStudio materials were already added or not.  I just assumed that, they had not been.

As I've described here https://github.com/mostaphaRoudsari/Honeybee/issues/398, I want the user to specify the climate and standard and the constructions will be assigned by default.

Assuming that **all** the OpenStudio constructions are always there (is this a fair assumption?) then I don't need to write any code that add the OpenStudio constructions and materials to Honeybee, instead I just need to focus on assigning the materials. Is this correct?

**Comment by mostaphaRoudsari** [comment]
It is a fair assumption. All you really need to do is to find the construction set based on climate zone and building type and then assign them (the construction) to each surface. The challenge is to get the right construction set from the json file.
