### ISSUE TITLE
PMV Microclimate map - Zones with irregular shape

### ISSUE THREAD

**Issue by NallaV** [mostaphaRoudsari/honeybee#590]
I am not sure if this is a bug or if the component only works for rectangular rooms.
I tried to calculate the PMV for 4 zones and I got the msg "The calculation has been terminated by the user" out of the "Microclimate Map anaysis" component. I realized it was because of one zone that is not rectangular but rather "T" shaped. The calculation worked for the rest of the zones.

**Comment by chriswmackey** [comment]
@NallaV ,

The microclimate map analysis is intended to work with all possible zone geometries, although E+ can only do simplified solar distribution calculations for T-shaped rooms (note that the microclimate map workflow still runs with this simplified solar).  In any case, you should not be getting that error and it is either happening because:
1) You have a mis-match between your versions of the components
2) Your zone geometry is not closed or is not correct.
3) You have found a bug that I should fix

Please pose a link to a GH file that recreates the error and I will have a look
-Chris

**Comment by NallaV** [comment]
Okay. The error was occurring because this zone's name included the letter "ö". I could never imagine that the zone name was somehow included in the PMV calculation. I usually avoid using letters other than standard Latin alphabet since I encountered errors before but this was an automated process so it took me a while to figure it out. The weird thing is that I had no problems with the Energy+ calculations or the LB PMV calculator. At any case, lesson learned.

**Comment by chriswmackey** [comment]
Ahh, Thanks for sharing the fix and non-Latin letter can definitely cause issues.

I would not have immediately guessed that having non-standard letters in the zone name would affect the PMV microclimate maps but I can tell you that the microclimate maps pull A LOT of data off of the zones.  In addition to the outputs from the Read EP Result component the list of zone properties includes but is not limited to:

1) Window transmittance values (for solar MRT calculation)
2) Floor reflectance values (also for solar MRT calculation)
3) Outdoor surface reflectance values (for solar MRT if test points outside of zones are included)
4) Zone Heights (for air stratification)
5) Window Heights (also for air stratification)
6) Surface view factors from each point to each zone surface
7) Sky view factors (through windows)

One of these might have not passed through the code well if there was a special character.
Thanks again for sharing!
-Chris
