### ISSUE TITLE
Simulating Street Lights

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/honeybee#592]
Hi @sariths,

I am reaching out with a question today.

When we perform illuminance simulation for a street light, should we not account for possible diffusion due to air pollution? If yes, what will be the best way to do that? Do we have some factor that we can use?

Thanks,
Devang

**Comment by sariths** [comment]
Hi @devngc,

Great question! There are actually no specific provisions within conventional lighting simulations to **photometrically mimic** the effect of pollution. As such, I am not aware if any lighting regulations call for it. AGI32, the lighting simulation software used by virtually every lighting engineer in North America, is a radiosity-based engine. So, surfaces have to be physically present in order for them to be included in the simulation. Radiance does have material called [mist](http://radsite.lbl.gov/radiance/refer/ray.html#Mist) which allows you to replicate at least part of the effect in a simulation. However, I am not sure if this aspect of Radiance has been physically validated.

What the standards do call for is a proper selection of [Light Loss Factor or LLF](http://www.ledsource.com/blog/light-loss-factor-explained/), which (among other things) accounts for the depreciation in lumens in polluted environments. For example, the amount of light "lost" due to dirt/pollution in a street will be a lot more than that in an office environment. 

LLF, whose value is always less than or equal to 1 and can be set through candelaMultiplier option in HB. A value between 0.7 to 0.5 is usually a safe choice for street lighting. 

Sarith

**Comment by devngc** [comment]
Thank you very much @sariths!
That is exactly what I was looking for. Thanks a lot.
-Devang

**Comment by chriswmackey** [comment]
@devngc and @sariths ,
Really great question and answer.  Thank you both for the intellectual stimulation!
