### ISSUE TITLE
E+ output in different order than the input zones

### ISSUE THREAD

**Issue by NallaV** [mostaphaRoudsari/honeybee#593]
I was running a simulation that included 16 zones and I realized that the results out of the ReadEPResult or ReadEPSrfResult component were not in the same order as the zones. 

My zones were named with a single number from 0 to 15. Even thought the zones were in numerical order (0,1,2,3,4....), I noticed that my results were appearing in order starting from 10 instead of 0 (10,11,12,13,14,15,0,1,2,3.....).

I fixed the problem by renaming the zones with a number starting from 10 to 25. 
I thought it was worth mentioning this here in case someone faces the same problem.

**Comment by chriswmackey** [comment]
@NallaV ,

Thanks for posting this.  It would be good to understand why this is happening and see if there is some way that I could correct it.  Would you mind posting a GH file that recreates the issue of the initial disordering?

-Chris

**Comment by NallaV** [comment]
Hi Chris,

I am sorry fot the delay. Here is an example (I couldn't upload it directly):

https://dl.dropboxusercontent.com/u/70479514/pub/Example.gh

I used a rather strange way to see if the zones' outputs are in the correct order as the initial zones. I compared the window area per zone. You can run the simulation with both sets of "ZONE NAMES" I have in the example and check the result.

//Nala

**Comment by chriswmackey** [comment]
@NallaV ,
Thank you for the very well-organized file.  Unfortunately, I was not able to run it because the zone geometry in the file was not closed:

![image](https://cloud.githubusercontent.com/assets/5567574/22810445/d3d281c2-ef06-11e6-8133-7e6aff4695f2.png)

Perhaps this may be the underlying cause of the issue?  Or maybe the incorrect geometry was internalized?

-Chris

**Comment by NallaV** [comment]
Hmm.. weird... Check this one. I updated it to the latest version of HB as well.

https://dl.dropboxusercontent.com/u/70479514/pub/Example%20(1).gh

//Nala

**Comment by mostaphaRoudsari** [comment]
is this a related issue?
http://www.grasshopper3d.com/group/ladybug/forum/topics/zonenames

**Comment by malshayeb** [comment]
Hi Chris and Mostapha,
Thank you for your time and the great plugin.
I've the same issue. I noticed that HB does not a sign the results to the correct zones !! I don't know if I'm doing something wrong. If so, please help me to fix it. I attached GH file and I explained the issue here:
http://www.grasshopper3d.com/group/ladybug/forum/topics/zonenames

In addition to what I explained at the link above, I also tried HB_Import_IDF to make sure of the names. The zone names were correct but the results were not. What make it weird is the results are changing by only changing the order of each zone is conceded to HB_Solve_Adjac. I've tried different computers and the issue still here. If you want to know when it happens, run a simulation of multiple zones and each coming from individual HB_Mass2Zone component. Run the simulation again of when one of the zone is passed through any other componant (like HB_BlazingCreater). You will see that you get a different result of the zone that you changed nothing on.

-Mohammed

**Comment by mostaphaRoudsari** [comment]
@chriswmackey do you know why this is happening or do you want me to take a look?

**Comment by chriswmackey** [comment]
@NallaV , @malshayeb , and @mostaphaRoudsari ,
Sorry for the incredibly late reply here.  I believe that I have fixed the issue as you see here:
http://www.grasshopper3d.com/group/ladybug/forum/topics/zonenames
and here:
https://github.com/mostaphaRoudsari/honeybee/commit/a3ef2ad4f274047b224a267bd7f2970400bd17f9
Let me know if you are still able to get the problem on your end.
