### ISSUE TITLE
Water HVAC systems

### ISSUE THREAD

**Issue by NallaV** [mostaphaRoudsari/honeybee#605]
Hello,
I have a project that has a ventilation system along with radiators and chillers. Is there any way I can add water systems besides ventilation? I remember there were some components that could do so. Are they not available any more? Is there any other way to do this? Thank you!

**Comment by chriswmackey** [comment]
@NallaV ,

Yes, you can simulate 15 HVAC templates with Honeybee.  The templates include hydronic systems like radiant slabs, chilled beams / baseboard, and fan coil units.  See here for how to simulate them:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Customizing_HVAC_Systems&slide=0&scale=1&offset=0,0

If these systems are not exactly what you are looking for, you can also create whatever HVAC system you want if you open Honeybee's generated .osm in OpenStudio.
-Chris

**Comment by NallaV** [comment]
Thank you for the reply. I guess that it is not possible to have both chillers and radiant floors at the same time directly in Honeybee. I found the components I meant in an earlier version of HB where you could set the flow rate and capacity of chillers/boilers and everything was part of a plant. I guess that now everything is autosized.

**Comment by chriswmackey** [comment]
@NallaV ,

The previous components in Honeybee did not usually work to set the size of components (either because they were broken or the sizing of one component does not change the overall capacity of the HVAC system). I added on variable on the airDetails to hard size the air system from honeybee, which changes everything in the air loop so that you actually see an effect on the simulation. Another option is to change the system sizing factors on the EP Simulation Parameters component, which changes the overall size of the heating or cooling systems. Finally, you can always open the osm in OpenStudio, go to the HVAC tab and set the size of individual components. You can rerun the osm from GH using the rerun OSM component.

**Comment by NallaV** [comment]
Thank you Chris!
