### ISSUE TITLE
Question regarding HVAC functions in Export to OpenStudio component

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/honeybee#610]
@chriswmackey @mostaphaRoudsari 

Just a quick question about the openstudio HVAC functions seen here:

https://github.com/mostaphaRoudsari/honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L795-L800

Did you adapt any of the code from the OpenStudio measures or did you simply convert all the code seen [here](https://github.com/mdahlhausen/scrappEplus/blob/master/OpenStudio/Measures/assign_zones_to_air_loop_by_csv/resources/OsLib_HVAC.rb) in OsLib_HVAC.rb to Python?

Could you go into a bit more detail about where you found the Ruby code for these functions?

Many thanks

**Comment by chriswmackey** [comment]
@antonszilasi ,

The code in the openstudio HVAC library is very much an adaptation and not a direct translation.  I only took the parts of the ruby code that were relevant to what we were trying to achieve in the Honeybee interface.  Most of the time, this was just to understand basic things like how to create an air loop or plant loop from scratch using OpenStudio SDK.  I also used it as a good source for default values since many of the values in there are taken from standards like ASHRAE 90.1 or the ASHRAE Advanced Energy Design Guides.  Everything else in Honeybee was stuff that I added in to make it work well with the inputs in the HB interface.

You found the file with basically all of the ruby code I adapted so I'm not sure what you are looking for in terms of more detail.

-Chris
