### ISSUE TITLE
Runtime Error (MissingMemberException)

### ISSUE THREAD

**Issue by jordaneasterling** [mostaphaRoudsari/honeybee#626]
Hi Ladybug Tools Team.

I've been having a difficult time running my rhino model into THERM via your work flow. Mostly, these have been issues with geometry that I am slowly working towards understanding better (I assume when importing Rhino arcs into THERM, there will typically be issues?)

Recently I got the following error:

===========================================================
Runtime error (MissingMemberException): 'NoneType' object has no attribute 'Component'
Traceback:
line 236, in checkTheInputs, "<string>"
line 972, in script
line 7844, in ___init___, "<string>"
===========================================================

Many times your response in these forums has been to updateHoneybee feature, but this is not solving the issue.

Any help would be greatly appreciated!

**Comment by chriswmackey** [comment]
@jordaneasterling ,
I apologize that the THERM workflow is a bit unstable at the moment as I've been updating everything to use the new THERM Command Line Interface (CLI), which will give us a whole set of new capabilities and make the workflow faster.  Everything should be complete by the end of this weekend.

The issue that you are experiencing is because you are using the newest version of Honeybee_Honeybee with an older "Create Therm Polygons" component.  Everything works on my end when I have both of these components up-to-date but I know that you would get the issue that you are reporting here if the two are out of sync.  Make sure that your "Create Therm Polygons" component is for MAY_08_2017 and everything should work.

Feel free to reopen the issue if the error persists.

**Comment by jordaneasterling** [comment]
Chris,

Thanks for the quick response. I'm traveling now but will check when I get back. 

jrdn

**Comment by chriswmackey** [comment]
@jordaneasterling ,

I finished implementing THERM Command Line Interface such that you can now run simulations directly from Grasshopper with no need to open the file in THERM.  I updated the hydra example file here to show how to do this:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=THERM_Export_Workflow&slide=0&scale=1&offset=0,0

Things should now be stable and everything should work as long as you are using components from the most recent version.  Let me know if you find otherwise.

-Chris
