### ISSUE TITLE
Energy output data orders mismatching the input zones' order

### ISSUE THREAD

**Issue by MingboPeng** [mostaphaRoudsari/honeybee#627]
Hi @mostaphaRoudsari @chriswmackey ,

Just went into a trouble when trying to do some calculations for each zones, and found the outputs' order for each zone does not match the input zones' order. please see the attachment, "testZone" is at the last of input zone, and the output results is at the first branch. 

Is this meant to be like this, or am I doing anything wrong?

![image](https://cloud.githubusercontent.com/assets/9031066/26204243/2c4435b6-3bac-11e7-8082-d72dd64c7bce.png)

Thanks,
Mingbo

**Comment by chriswmackey** [comment]
@MingboPeng ,

This issue was recently fixed:
https://github.com/mostaphaRoudsari/honeybee/issues/593
http://www.grasshopper3d.com/group/ladybug/forum/topics/zonenames
https://github.com/mostaphaRoudsari/honeybee/commit/a3ef2ad4f274047b224a267bd7f2970400bd17f9

Update your components and all should work.  If the issue persists, reopen this and post a link to a GH file that recreates the error.

-Chris

**Comment by MingboPeng** [comment]
@chriswmackey  that's strange, I just updated all my components before build up this grasshopper. 
I just did another update, and "readEPResult" is still 2/15/2017 version.
