### ISSUE TITLE
3 and 5 phase method in Honeybee

### ISSUE THREAD

**Issue by Mahamiho** [mostaphaRoudsari/honeybee#628]
Hey,
I have a project where I would need to test the 3 and 5 phase methods to simulate light shelves, anidolic systems, and reflective surfaces. I heard that there is going to be a release soon of these features in Honeybee, is it sure now when is that going to be?
Thanks alot,

**Comment by sariths** [comment]
@Mahamiho There are some [examples](https://github.com/ladybug-tools/honeybee-plus/tree/master/plugin/grasshopper/sampleFiles) from the [NYC AEC hackathon](http://core.thorntontomasetti.com/aec-technology-symposium-and-hackathon-2016/aec-technology-symposium-and-hackathon-2016-workshops/) that contain implementations of the Three Phase Method in Honeybee. However, I am not sure if they'd still be functional due to the changes we've made to the code. It will at least be 2-3 weeks (or more) before we have a stable implementation of the Three Phase Method.

**Comment by Mahamiho** [comment]
Hey @sariths thanks for your reply, I will wait for it then :)

**Comment by mostaphaRoudsari** [comment]
They are still functional in grasshopper but I would wait until we address this new enhancement: https://github.com/ladybug-tools/honeybee/issues/131

**Comment by chriswmackey** [comment]
@Mahamiho ,

For the sake of keeping our github issues tidy, I just wanted to point out that the implementation of 3 and 5 phase method is happening on the HoneybeePlus github repository and not this one. So you should keep a lookout here for when 3 and 5 phase are implemented:

https://github.com/ladybug-tools/honeybee

I'm going to close out this issue on this repo, which is just the Honeybee legacy version and will not have any implementation of 3 or 5 phase.

-Chris
