### ISSUE TITLE
GrizzlyBear "model" Missing?

### ISSUE THREAD

**Issue by EnricoBH** [mostaphaRoudsari/honeybee#636]
Hi everyone,
I just updated to the new HB+LB (0.0.61 + 0.064) and noticed that the option for linking the OpenStudio to the GrizzlyBear component is missing. Just adding a new output and calling it "model" seem to solve the issue.
Was wondering if this is the right way to extract the correct model for?

Cheers

**Comment by mostaphaRoudsari** [comment]
Hi @EnricoBH, That is the right approach and if the output is missing that is a bug that should be fixed. Thanks for reporting.

**Comment by chriswmackey** [comment]
@EnricoBH and @mostaphaRoudsari ,

I have never used the Grizzy Bear components but I can try to address the issue.  As far as I can tell, the GBXML importer still has a model output on it:
![image](https://user-images.githubusercontent.com/5567574/28296344-c2fd0f38-6b35-11e7-95c7-035d9ad1b312.png)

Could you elaborate or upload a GH definition showing the issue?
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey this is how the workflow used to be. These components use OpenStudio to import/export gbXML.

![image](https://user-images.githubusercontent.com/2915573/28296695-c09beb18-6b37-11e7-8f07-0ff385ac6271.png)

As @EnricoBH mentioned the fix is just to add an output for model. I have already exposed it in the outputs that are returned from the main function.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Understood.  I did not realize that the component was using the actual model object and not the OSM.  I have put back the model output and everything should work fine now:
https://github.com/mostaphaRoudsari/honeybee/commit/46993c36f490718a99be3cc8e9bbaa60000a950b
-Chris
