### ISSUE TITLE
Seasonal Schedule bug

### ISSUE THREAD

**Issue by FilippoIT** [mostaphaRoudsari/honeybee#677]
Hi guys, 
I post here a bug I may have obtained on the Seasonal Schedule component following Abraham suggestion to switch my thread from the Honeybee forum to here.

Long Story short, the seasonal schedule component creates some overlapping days.
This is my Seasonal schedule file with the problem highlighted
[https://www.dropbox.com/s/j0ygtw0x5xymswd/Seasonal_schedule_3.gh?dl=0](url)
This is the former Honeybee Forum thread:
http://discourse.ladybug.tools/t/seasonal-schedule-issue/2553/9 (issue shown in the post of the 14th of February)

thank you very much for your kind support!

Filippo

**Comment by chriswmackey** [comment]
@FilippoIT ,
I apologize for such a late response.  Somehow, your email fell through the cracks on a busy week.  There is, indeed, a bug in the seasonal schedule and I will investigate it now to see if I can fix it. I'll report back here shortly.

**Comment by chriswmackey** [comment]
The issue was a small typo with some big consequences for the output.  I fixed the bug here:
https://github.com/mostaphaRoudsari/honeybee/commit/693ddf5f615e56202fb68a6365b9b473ad41cf53

If you sync you components with the github, you should be able to use the seasonal schedule component without issues.
