### ISSUE TITLE
Question Regarding Simulated illuminance data Vs. Measured Data Difference

### ISSUE THREAD

**Issue by DavidZTian** [mostaphaRoudsari/honeybee#682]
Dear All,

Thanks for the previous help on modeling using Ladybug+Honeybee. I encountered a problem with the difference of illuminance vlaues between measured data and Honeybee simulated data. Interesting engough, the major difference happened in the positions 2 m away from east and west side walls. In the simulation results, the highest illuminance data happens on 4 m away from walls and positions 2m away from wall have very low illumiance values. However, measured data show the positions 2 m away from wall have the highest illuminance values. The simulation used climate sky and real weather data for the year. The reflectance of ceiling, wall, floor are set as 0.8, 0.6, 0.3; the bounce is set as 4. The results and radiance paramter setting are attached. Can any one give suggesions on what could be the reasons?
Thanks a lot.
![default](https://user-images.githubusercontent.com/29589369/38162015-093e5998-350c-11e8-8943-f88cc02a0334.png)

David

**Comment by chriswmackey** [comment]
@DavidZTian ,
This issue does not have to do with any bugs or new features in the Honeybee software and so it belongs on [our forum](http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8) instead of the github here.  Accordingly, I am closing out this issue and I will respond with some possible explanations for your mis-match with your measured results after you post the question to the forum.
