### ISSUE TITLE
What are the R/U-values of the insulation materials?

### ISSUE THREAD

**Issue by emccormi** [mostaphaRoudsari/honeybee#696]
I've recently started using the THERM plug in - great job and THANK YOU!  I'm a little confused, though.  Honeybee seems to think that my insulation materials are windows?  I'm trying to identify the R-values (SI) and nothing is popping up with the Decompose EP Construction command.  Why is it saying "
![hb1](https://user-images.githubusercontent.com/23248062/40992128-7dcae1fe-68bb-11e8-8a15-7c3c127f5d1c.JPG)
![hb3](https://user-images.githubusercontent.com/23248062/40992129-7dec4f06-68bb-11e8-916a-f6939cd198dd.JPG)
![hb2](https://user-images.githubusercontent.com/23248062/40992131-7e0655ea-68bb-11e8-824a-250f368ae2fa.JPG)

<null>"?

**Comment by saeranv** [comment]
@emccormi  It's best to post these kind of questions on the Ladybug-tools forums: https://discourse.ladybug.tools/

My guess on what is happening here is that because unlike in E+, a THERM R-value (m2K/W) is based on thickness taken from an input geometry. Therefore the THERM material definition doesn't include R-value, it must be derived from the provided geometry. 

That's why conductivity is provided instead. If you want to find the R-value, just take the conductivity (provided), and just: 1/(conductivity / thickness ), where thickness is taken from your input geometry.

**Comment by emccormi** [comment]
Thanks, I knew there had to be a better place to post.  Thanks also for your feedback - I'll look into calculating the R value from the conductivity.

**Comment by chriswmackey** [comment]
Thanks for taking care of this @saeranv .  I'm closing out this issue and I'll see you on the forums!
