### ISSUE TITLE
Honeybee Generation is Now Fully-Functional  missing HB_HB update

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#705]
Hi @chriswmackey,
I believe the HB_HB should also be synced to the github. The example in hydra uses September 11 and the github is September 4. The later makes the PV components to fail.
Thanks,
-A.

**Comment by ayezioro** [comment]
Hi,
In the meantime i've found an issue with the PVgen component.
Having more than one surface plugged into te _HBSurfaces input, you have to input 2 (or more) values into the _cellsEfficiency input. It doesn't take only one value and complains of:

> 
> > 1. The length of a list of inputs into either _name_,_cellsEfficiency 
> > _integrationMode,_NoParallel,_Noseries,costPVgen_ or _powerOutput 
> > is longer than the number of Honeybee surfaces connected to this component!
> > e.g if you have 2 Honeybee surfaces you cannot have 3 values input into costPVgen_!
> Please check the inputs and try again!

and the PV_HBSurfaces output gives a value of -1.

Other inputs do accept one value.

Didn't catch in the code where to fix it ... :-(

-A.

**Comment by hopezh** [comment]
Dear @chriswmackey, 

I encountered the following error using the latest PVgen component. As shown in the image attached it seems to be an issue I reported in [this post ](https://discourse.ladybug.tools/t/pv-simulation-doesnt-work/3313/13?u=grasshope) that PVgen component doesn't recognize the other PV surfaces other than the first one. 

Appreciate if you can kindly advise which part of the code in PVgen I shall look into to debug this issue. 

Thanks. 

Ji (Grasshope) 

![screen shot 2018-09-29 at 10 24 14 pm](https://user-images.githubusercontent.com/23435810/46247265-6fa50380-c43b-11e8-9a02-a10ed37b70b7.png)

[PVgen_issue_v003_usingTheNewPVgenCompnent.zip](https://github.com/mostaphaRoudsari/honeybee/files/2430751/PVgen_issue_v003_usingTheNewPVgenCompnent.zip)

**Comment by chriswmackey** [comment]
@ayezioro and @hopezh ,
I apologize for such a late response and thank you for finding this issue.  It seems to have fallen through the cracks as I was amidst the craziness of working two jobs.  I have corrected the issue here:
https://github.com/mostaphaRoudsari/honeybee/commit/165531230d02331b4bde23150adc84342d8a7dc7
And I updated the hydra version accordingly:
https://github.com/chriswmackey/hydra_2/commit/19d7b205ca985dfafcca39f96134b705a5b72d1b

I also added in the ability to set a single efficiency for multiple surfaces.

One thing that I noticed is that there appear to be some bugs in with using Photovoltics in the latest version of  OpenStudio so I recommend using OpenStudio 2.5 with the PV generators for now.  If you happen to figure out why the newest OpenStudio is returning 0 power for the PVs, open another issue and I will fix it.  It definitely seems to be something on the OpenStudio / E+ side, though, if it's working in previous versions.

**Comment by hopezh** [comment]
Dear Chris, 

Thank you very very much for checking and updating the PVgen compoent. 

I did a quick test and found the following two issues:

1. The PV electricity results generated from the newPVgen+OpenStudio workflow is significantly different from that from the oldPVgen+EPlus workflow. The difference is shown below which is based on the html reports generated. 

![difference in pv electricty results btw new and old pvgen components](https://user-images.githubusercontent.com/23435810/47765576-9473eb80-dd05-11e8-9e4b-e6bdebfd28df.png)


2. Four whole building electricity related output variables as requested from the workflow are missing from the newPVgen+OpenStudio workflow as compared to that from the the oldPVgen+EPlus workflow.

2.1 generator and electricity related output variables from the oldPVgen+EPlus workflow, and the top four variables are missing from the newPVgen+OpenStudio workflow.

![generator related output variables from the old pvgen eplus workflow](https://user-images.githubusercontent.com/23435810/47765610-bcfbe580-dd05-11e8-9318-dd03beb8b22c.png)

2.2 generator and electricity related output variables from the newPVgen+OpenStudio workflow.

![generator related output variables from the new pvgen openstudio workflow](https://user-images.githubusercontent.com/23435810/47765627-cf761f00-dd05-11e8-8282-e016d14888ef.png)


The **two GH workflows** and the **Excel file** comparing the difference are attached for your reference. 

Please let me know if I missed something important here. 

Thank you for your kind assistance, again. 
Ji

[PVgen_issue__using_newPVgen_and_OpenStudio.zip](https://github.com/mostaphaRoudsari/honeybee/files/2532639/PVgen_issue__using_newPVgen_and_OpenStudio.zip)

**Comment by ayezioro** [comment]
Thanks @chris for the update and thanks @hopezh for the checking.
-A.

**Comment by ayezioro** [comment]
OMG!!

**Comment by hopezh** [comment]
Dear @chriswmackey , I noticed what you mentioned above, and it seems you're right that the problem is with **OpenStudio**. 

The **newPVgen+newEPlus** components can produce the same results as that from the **oldPVgen+oldEPlus** components, as shown below.

![image 7](https://user-images.githubusercontent.com/23435810/47770531-b5930700-dd1a-11e8-8161-d8f03ba0fad1.png)

I suspect it is related to the four output variables missing from the results file generated by OpenStudio, or some of them... 

@ayezioro  what do you think? 

BTW, the Excel table shown in my previous post is not correct because I was using 0.9 for inverter efficiency in the oldPVgen+oldEPlus workflow which should be 0.98 which was used in the workflow for the newPVgen+OpenStudio workflow. 

The updated comparison chart still shows significant difference:

![image 9](https://user-images.githubusercontent.com/23435810/47770837-e45dad00-dd1b-11e8-9fc3-6fb6db444bce.png)

**Comment by chriswmackey** [comment]
Ok, I realized that there was a bug in the old code here:
https://github.com/mostaphaRoudsari/honeybee/commit/0658b2b8ae40b10fd5d0815feb70afc8ffd964d0

I believe that commit should fix it and let me know if you are unable to recreate the old results, @hopezh

**Comment by chriswmackey** [comment]
Thanks for letting me know @hopezh ,
Now, I think it is probably the E+ Run Simulation component that is not correct and I will take a look when I get the chance.

**Comment by hopezh** [comment]
I'm trying to use a "horrified" emoji here which is not available here obviously...

**Comment by chriswmackey** [comment]
There is a horrified emoji:
:astonished:

Thankfully, we don't need to use it here.  I can see that I'm not inputting the PV efficiency correctly into the OpenStudio workflow.  I will try to fix the OpenStudio component now.

**Comment by chriswmackey** [comment]
Ok.  Now I have gone through and verified for myself that the OpenStudio component and the Run Simulation component give the same exact results for a range of cases:
https://github.com/mostaphaRoudsari/honeybee/commit/cea35ac7af89d73ee37a54c8624982ddd2155de4

While I have learned to never say never, I am 99% sure that this has finally fixed the issue.
So now I think a 😄 is appropriate!

**Comment by hopezh** [comment]
Dear @chriswmackey , thank you very much for the update! (followed by multiple emoji of "thumbs up" and "applauding"). Glad that you left a 1% chance for debugging. 

Yes, the calculation for **PV electricity production** is consistent btw the old and new PVgen, EPlus and OpenStudio components. 

However, there are still differences, although small, in cooling and heating energy results.

As shown below, assuming the results produced by the old EPlus component is the baseline, the new EPlus and the new OpenStudio components will provide overestimation in both cooling and heating loads, which leads to the difference in total site energy related results. 

![image 2](https://user-images.githubusercontent.com/23435810/48339222-a741d500-e6a2-11e8-9221-c14927a4c070.png)


I wonder if there is any change in **shading related calculation** in the latest EPlus and OpenStudio components .... as this is the only factor I can think of that will affect cooling and heating in this case.  

Will do some tests using even simpler model later. 

Meanwhile, pls take a look of the GH example files and let me know if I missed anything important here. 

-Ji

[2018-11-12 test new PVgen & new OpenStudio.zip](https://github.com/mostaphaRoudsari/honeybee/files/2571371/2018-11-12.test.new.PVgen.new.OpenStudio.zip)

**Comment by chriswmackey** [comment]
@hopezh ,

Thank you for verifying the results with your scripts.

If I am reading your chart correctly, the difference between the Eplus and OpenStudio component results is just ~1%, which really is not a significant difference for an energy model.  The OpenStudio and Eplus components have all inputs matching except for a small difference on the ideal air loads system.  The OpenStudio component is using a detailed ideal air load system while the EPlus component uses a more simplified ideal air load template.  This can result in a difference of results around 1% but it really isn't significant since both systems have the same parameters set on them.  If you are going to worry about differences that small, you really should not be using an ideal air load system, which is pretty far from modeling a real, fully-detailed HVAC system.  In fact, I would be cautions about labeling the results of the ideal air loads system as "district heating" and "district cooling" since its rare that the heat added/removed from district heating/cooling water will align with ideal air loads perfectly.

If you manage to verify if the results are specifically the result of shading or PV differences, I can take a deeper look.  But, from my perspective, it looks like this is just the result of the minor difference in ideal air loads systems.

**Comment by hopezh** [comment]
Dear @chriswmackey , thanks for the clarification. 

Yes, the good news is that the difference in results btw the new EPlus and the new OpenStudio components are not very big. 

I did another test using a larger model with about 80+ zones. The comparison is shown below. 

I'm curious about the small difference in modeling the ideal loads air system btw the OpenStudio and EPlus components. Maybe I shall read the idf files generated in this regard?  

Also, it is duly noted agreed that the use of ideal loads air system is to estimate thermal loads rather than actual energy consumption which depends on HVAC settings such as COP.  

![image 4](https://user-images.githubusercontent.com/23435810/48761604-04153f00-ece4-11e8-9abb-4ca211be3a9f.png)

[2018-11-20 test new PVgen & new OpenStudio.zip](https://github.com/mostaphaRoudsari/honeybee/files/2598836/2018-11-20.test.new.PVgen.new.OpenStudio.zip)

**Comment by chriswmackey** [comment]
@hopezh ,
I think that the difference in the two ideal air loads systems comes from the fact that the OpenStudio ideal air loads system is actually being sized according to the cooling/heating design days while the E+ one is an infinite capacity system.  So given this, the OpenStudio ideal air loads system results should always be a little lower than the E+ one because the OpenStudio one hits its maximum capacity at a few hours in the simulation.
